### ISSUE TITLE
Gaomon S620 Uses Different Input Report Length Than Configuration

### ISSUE THREAD

**Issue by Zothin** [InfinityGhost/OpenTabletDriver#115]
the driver searched for tablets and didn't find my s620 I tried researching and it failed again.

**Comment by InfinityGhost** [comment]
Logs? Platform? Version?

**Comment by Zothin** [comment]
Latest Version 0.3.1 on Windows 10 
[4-4-2020.log](https://github.com/InfinityGhost/OpenTabletDriver/files/4430250/4-4-2020.log)

**Comment by InfinityGhost** [comment]
Open OpenTabletDriver, go to the configuration manager under the Tablets menu. In the configuration manager there is a devices tab. Send a screenshot of the contents of the tab.

**Comment by Zothin** [comment]
http://prntscr.com/rsm98d

**Comment by Zothin** [comment]
as far as i can see in my device registers my s620 as a Gaomon Tablet with a maximum Input report length of 10. In the devices the s620 has a 12 IRL and the vendor id and product id are identical if this is of any help

**Comment by InfinityGhost** [comment]
Lets try a newer build to see if this is fixed already. https://github.com/InfinityGhost/OpenTabletDriver/suites/560137891/artifacts/3635112

**Comment by Zothin** [comment]
kk

**Comment by Zothin** [comment]
It's 2 am here and the fact that you replied and took the time to help me instantly is commendable. Thanks.

**Comment by Zothin** [comment]
Still no tablet found.

**Comment by Zothin** [comment]
Wait i changed the IRL in the configurator and this happened
[2.15 4-4-2020.log](https://github.com/InfinityGhost/OpenTabletDriver/files/4430318/2.15.4-4-2020.log)

**Comment by InfinityGhost** [comment]
Do you happen to have the Gaomon driver installed?

**Comment by Zothin** [comment]
No I had your hawku version before but windows kept detecting a virus so i just got otd

**Comment by InfinityGhost** [comment]
Uninstall the vmulti drivers and reboot

**Comment by Zothin** [comment]
On it

**Comment by Zothin** [comment]
Where does one find the vmulti drivers?

**Comment by InfinityGhost** [comment]
It's in the releases of hawku's tabletdriver, https://github.com/hawku/TabletDriver/releases/download/v0.2.3/TabletDriverV0.2.3.zip

**Comment by Zothin** [comment]
Found it and im rebooting

**Comment by Zothin** [comment]
I have succesfully rebooted and launched otd with no success

**Comment by InfinityGhost** [comment]
Send a screenshot of the devices tab and any of the Gaomon Tablet devices' pages

**Comment by Zothin** [comment]
http://prntscr.com/rtxa1i
http://prntscr.com/rtxaam
Here they are

**Comment by InfinityGhost** [comment]
Modify the `Configurations/Gaomon/S620.json` file to contain this: 
```json
{
  "Name": "Gaomon S620",
  "VendorID": 9580,
  "ProductID": 109,
  "InputReportLength": 12,
  "ReportParser": "TabletDriverLib.Vendors.Gaomon.GaomonReportParser",
  "CustomInputReportLength": 10,
  "CustomReportParser": "TabletDriverLib.Vendors.Gaomon.GaomonReportParser",
  "Width": 165.1,
  "Height": 101.6,
  "MaxX": 33020.0,
  "MaxY": 20320.0,
  "MaxPressure": 8191,
  "ActiveReportID": 10,
  "AuxReportLength": 0,
  "AuxReportParser": null,
  "FeatureInitReport": null
}
```

**Comment by InfinityGhost** [comment]
This issue may be the result of a dirty installation it turns out, most tablet driver uninstallers don't clean up like they should and lead to improper initialization of the device.

**Comment by doubledge-spec** [comment]
I tried all of the things mentioned in this thread, still doesn't detect s620

**Comment by doubledge-spec** [comment]
> I tried all of the things mentioned in this thread, still doesn't detect s620

I had to uninstall the Gaomon drivers for it to detect, seems kinda backwards considering that Your Tablet Driver fork from hawku needs it.

**Comment by InfinityGhost** [comment]
> > I tried all of the things mentioned in this thread, still doesn't detect s620
> 
> I had to uninstall the Gaomon drivers for it to detect, seems kinda backwards considering that the Tablet Driver fork from hawku needs it.

I'll consider this the fix then.
