### ISSUE TITLE
Pressing the pen onto the tablet stops mouse movement until the pen is lifted again

### ISSUE THREAD

**Issue by kangalioo** [InfinityGhost/OpenTabletDriver#122]
## Description
Pressing the pen onto the tablet stops mouse movement until the pen is lifted again. I don't even know if it's a feature or a bug, because I suppose this is useful for people who use their pen like a computer mouse. It's unwanted behavior for many other use cases though.

It would be good to be able to toggle this behavior.

## System Information:

Option            | Value
------------------|------------------
Operating System  | Arch (Antergos) Linux x64, KDE
Software Version  | v0.2.0-rc1
Tablet            | Wacom PTH-451

**Comment by InfinityGhost** [comment]
We're gonna need some capture of the tablet debugger between when the pen is pressing and when its not.

**Comment by kangalioo** [comment]
I recorded a video of the Tablet Debugger here: https://streamable.com/1h7zez

You can see whether I'm currently pressing or hovering from the `Pressure` property.

**Comment by InfinityGhost** [comment]
Try this build
https://github.com/InfinityGhost/OpenTabletDriver/suites/641017376/artifacts/5359286

**Comment by kangalioo** [comment]
It works perfectly as far as I can tell. Not sure if I should close this issue now

**Comment by InfinityGhost** [comment]
Don't close the issue manually, the pull request merge will close it.
