### ISSUE TITLE
Can't use my tablet in OneNote + no pen pressure in Photoshop

### ISSUE THREAD

**Issue by shader301202** [InfinityGhost/OpenTabletDriver#131]
## Description
Tablet works fine in Osu. I cannot use it in OneNote or Windows Ink Sketchpad as it detects it as mouse? and I cannot draw. It works in Photoshop except there is no pen pressure. How can I fix this? Or is it by design (that the drivers only work in osu)?

edit: I believe this is may be caused by the fact the Windows Ink is disabled in these drivers? If that's the case, is there a way to disable/enable them by application (or to disable it for osu but enable it for everything else)?

## System Information:
Option            | Value
------------------|------------------
Operating System  | Windows 10 x64
Software Version  | 0.2.0-rc1
Tablet            | Gaomon S620

**Comment by InfinityGhost** [comment]
Windows Ink has to be added manually in order to support pen pressure. It's in the plans to add it but as of right now its not supported.

**Comment by shader301202** [comment]
Alright, thanks for the answer! :D  

I will follow the releases while waiting for the feature ;p

**Comment by InfinityGhost** [comment]
I'd suggest following [this project](https://github.com/InfinityGhost/OpenTabletDriverPlugins) in that case, however it will only be published as binaries with future releases.
