### ISSUE TITLE
Star G640 Not Detected, Possibly new revision

### ISSUE THREAD

**Issue by skyborgff** [InfinityGhost/OpenTabletDriver#132]
## Description
Star G640 Isn't detected, aparently its a new revisio
![image](https://user-images.githubusercontent.com/19365140/81852880-9d2cbb00-9553-11ea-8b7c-4769ddde64dd.png)
![image](https://user-images.githubusercontent.com/19365140/81852892-a3229c00-9553-11ea-9490-eb80a4a80927.png)

## System Information:
Operating System  Windows 10
Software Version  v0.2.0-rc1
Tablet            G640

**Comment by InfinityGhost** [comment]
Export a diagnostic report and send it here. Use [this](https://github.com/InfinityGhost/OpenTabletDriver/suites/660195867/artifacts/5800779) version which has diagnostic report support.

**Comment by InfinityGhost** [comment]
Input Report Length: 12
Still unsure if this is a different revision or something though
