### ISSUE TITLE
Configuration overall does nothing (gaomon s620)

### ISSUE THREAD

**Issue by Mrcubix** [InfinityGhost/OpenTabletDriver#136]
## Description
Configuration overall does nothing.
uninstalled the OEM drivers, rebooted, the tablet work, this tool now detect my tablet, but when i edit anything, it just doesn't work after applying them.
It's possible however that i'm missing some step in the driver installation, cause you had to install a vmulti driver with the hawku one's

## System Information:

Option            | Value
------------------|------------------
Operating System  | Windows 8.1 x64
Software Version  |  0.20--rc1
Tablet            |  Gaomon s620

**Comment by ssccoonniicc** [comment]
Gaomon s620 support on windows is pretty hit **or** miss. OTD _in most cases_ does not need a driver to be installed for it to work. If the vmulti driver is still installed then try to uninstall it. Also in OTD click on the tablets button on the top and then open tablet debugger. Then move your pen around on your tablet and tell me if and thing changes in the debugger.

**Comment by Mrcubix** [comment]
nothing happen in the debugger, no vmulti driver installed

**Comment by skyborgff** [comment]
Just to clarify, it detects, and moves, but changing the areas doesnt "apply"?

**Comment by Mrcubix** [comment]
There is the msg about the setting getting applied, but nothing change on the tablet

**Comment by Mrcubix** [comment]
ok, now it work for some reason on desktop, but it doesn't work ingame in osu

**Comment by Vlothx** [comment]
Please disable raw input.

**Comment by Mrcubix** [comment]
already disabled

**Comment by InfinityGhost** [comment]
> EDIT: worked after restart, thx, still it's strange that OTD started working randomly
> 
> other than this, is there any way to make OTD work in background?

Not right now, but after #130 is merged it'll be the default.
