### ISSUE TITLE
Tablet not getting detected

### ISSUE THREAD

**Issue by DavidStojko** [InfinityGhost/OpenTabletDriver#142]
Tablet is not getting detected due to this error

[Error:HidSharp.Exceptions.DeviceIOException]	Unable to open HID class device (OK).

Operating System  | kubuntu 19.10 x86_64
Software Version  | 0.2.0-rc1
Tablet            | CTL-471

**Comment by jjhhgg100123** [comment]
Just to check, have you tried the solution in the [wiki?](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ)

**Comment by InfinityGhost** [comment]
Run `sudo usermod -aG $user users`
