### ISSUE TITLE
how to install it

### ISSUE THREAD

**Issue by meowzy0** [InfinityGhost/OpenTabletDriver#145]
yes i am stupid

**Comment by LavaDesu** [comment]
[Download the driver](https://github.com/InfinityGhost/OpenTabletDriver/releases/download/v0.2.0-rc1/OpenTabletDriver.win-x64.zip), extract it to a folder, and open the `OpenTabletDriver` file inside.

**Comment by meowzy0** [comment]
but after that my cursor is not moving

**Comment by meowzy0** [comment]
i am not that stupid then

**Comment by skyborgff** [comment]
Disable raw input in osu!

**Comment by meowzy0** [comment]
i mean it is not working even on my desktop

**Comment by skyborgff** [comment]
could you join the discord so we can troubleshoot?

**Comment by Mrcubix** [comment]
Kill OEM drivers in task manager
