### ISSUE TITLE
cursor glitched

### ISSUE THREAD

**Issue by a0g-402** [InfinityGhost/OpenTabletDriver#147]
## Description

the cursor sometime glitch
i cant fc any song ;(
[https://youtu.be/fHUvO4to5hk](url)
## System Information:

Option            | Value
------------------|------------------
Operating System  | Windows 10 Home
Software Version  | 0.2.0--rc1
Tablet            | Wacom CTL-471

**Comment by Vlothx** [comment]
At least on the video you sent, looks like there's another driver running in the background.

**Comment by InfinityGhost** [comment]
Try [this build](https://github.com/InfinityGhost/OpenTabletDriver/suites/737612381/artifacts/7454795) to see if the problem still occurs.

**Comment by a0g-402** [comment]
> Try [this build](https://github.com/InfinityGhost/OpenTabletDriver/suites/737612381/artifacts/7454795) to see if the problem still occurs.

I tried, problem still occurs but more rarely
I will try other drivers

**Comment by a0g-402** [comment]
ok i know what caused it sorry for wasting your time
