### ISSUE TITLE
de-AIDS the zip

### ISSUE THREAD

**Issue by nerd** [InfinityGhost/OpenTabletDriver#149]
good god please what the fuck is this directory structure

**Comment by Vlothx** [comment]
What do you mean?

**Comment by InfinityGhost** [comment]
Please provide useful feedback and suggestions to improve instead of useless complaints.

**Comment by nerd** [comment]
please provide a useful release file. why are there like 7 nested directories? that's gross as hell

**Comment by Vlothx** [comment]
You're free to check the Actions page if you want compiled binaries :<

**Comment by InfinityGhost** [comment]
Are you talking about the build artifacts? Release binaries won't be done the same way as artifacts.
