### ISSUE TITLE
OTD does not detect Gaomon s620

### ISSUE THREAD

**Issue by doubledge-spec** [InfinityGhost/OpenTabletDriver#170]
## Description

The driver does not detect the s620 but detects a device "Gaomon Tablet". both have identical vendor and product id's.
![image](https://user-images.githubusercontent.com/56917537/86942951-d2005d00-c113-11ea-9686-ffffc92a01c4.png)
![image](https://user-images.githubusercontent.com/56917537/86943037-e9d7e100-c113-11ea-8f87-6a0a5789da44.png)
![image](https://user-images.githubusercontent.com/56917537/86943156-168bf880-c114-11ea-8146-eeaef0831805.png)

## System Information:

Option            | Value
------------------|------------------
Operating System  | Ubuntu
Software Version  | 20.04 LTS
Tablet            | Gaomon s620

**Comment by doubledge-spec** [comment]
same issue I had with Windows 10 a couple of months ago. This is a fresh install of Ubuntu 20.04 LTS.

**Comment by ssccoonniicc** [comment]
add `blacklist hid-uclogic` to /etc/modprobe.d/blacklist.conf, download [this file](https://cdn.discordapp.com/attachments/723399565780189234/729075215581184022/30-opentabletdriver.rules) and put it in /etc/udev/rules.d/ and then restart your computer.

**Comment by doubledge-spec** [comment]
yeah I am new to linux, but I can figure this out thanks @ssccoonniicc

**Comment by InfinityGhost** [comment]
Marking closed based on last reply.
