### ISSUE TITLE
[Feature Request] Plugin additions

### ISSUE THREAD

**Issue by skyborgff** [InfinityGhost/OpenTabletDriver#174]
## Multiple requests

- A way to specify what binds a binding can have
- Having absolute and relative mode as functions, so devs am able to reuse the code instead of copying it
- A button to run functions inside a plugin

**Comment by InfinityGhost** [comment]
> Having absolute and relative mode as functions

This will come with moving `AbsoluteMode` and `RelativeMode` to TabletDriverPlugins so it can be inherited and overridden

> A button to run functions inside a plugin

This will only work by running static methods, from that point the plugin developer will have to decide how to handle the invocation
