### ISSUE TITLE
CTL-4100 is not actually supported

### ISSUE THREAD

**Issue by Remyria** [InfinityGhost/OpenTabletDriver#195]
## Description

Installed, didn't work properly, cursor just did whatever.
Tried some things like restarting the driver, uninstalling and reinstalling vmulti from hawku in case it interfered, reinstalling OTD, changed the directory of bin, changed sensitivity, screen and tablet areas, NOTHING had the slightest impact on how well it worked.

## System Information:

Option            | Value
------------------|------------------
Operating System  |  W10 Family
Software Version  |  v0.3.0
Tablet            |  Wacom CTL-4100 (Intuos S Small)

**Comment by InfinityGhost** [comment]
Moved the [card](https://github.com/InfinityGhost/OpenTabletDriver/projects/4#card-31065001) from Supported -> Nonfunctional

**Comment by InfinityGhost** [comment]
Closing this issue because of #199, this issue moved the tablet from untested -> broken.
