### ISSUE TITLE
Can't find OpenTabletDriver.exe in my folder

### ISSUE THREAD

**Issue by brakence** [InfinityGhost/OpenTabletDriver#211]
I'm sorry in advance for being pretty clueless about all this stuff. I tried downloading the latest release of OpenTabletDriver so I could connect it to my Gaomon S620. I attempted to run OpenTabletDriver.Daemon.exe but only a text script appeared with nothing else happening.

**Comment by X9VoiD** [comment]
OpenTabletDriver have two separate components to launch.

The first being the daemon, OpenTabletDriver.Daemon.exe

And then the UI,
`OpenTabletDriver.UX.Wpf` for Windows.
`OpenTabletDriver.UX.Gtk` for Linux.
`OpenTabletDriver.UX.MacOS` for MacOS.

**Comment by InfinityGhost** [comment]
Assuming you're running Windows, I would suggest using the installer [here](https://github.com/InfinityGhost/OpenTabletDriver.Installer/releases/tag/v0.3.0.2). It handles updates and the two executables for you.

**Comment by InfinityGhost** [comment]
No response in almost a week, assuming resolved.

**Comment by Airkek** [comment]
When I trying to start Daemon - it says 
`fail: JKang.IpcServiceFramework.Hosting.NamedPipe.NamedPipeIpcEndpoint[0]
      Error occurred
System.AggregateException: One or more errors occurred. (Some or all identity references could not be translated.)
 ---> System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
   at JKang.IpcServiceFramework.Hosting.NamedPipe.NamedPipeIpcEndpoint`1.WaitAndProcessAsync(Func`3 process, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---`
![image](https://user-images.githubusercontent.com/45855057/91090810-5411fa00-e65e-11ea-8c16-4f20a8859f08.png)

**Comment by Airkek** [comment]
![image](https://user-images.githubusercontent.com/45855057/91090877-7146c880-e65e-11ea-9c01-49320c71328f.png)

**Comment by InfinityGhost** [comment]
> When I trying to start Daemon - it says
> `fail: JKang.IpcServiceFramework.Hosting.NamedPipe.NamedPipeIpcEndpoint[0] Error occurred System.AggregateException: One or more errors occurred. (Some or all identity references could not be translated.) ---> System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated. at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess) at System.Security.Principal.NTAccount.Translate(Type targetType) at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified) at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule) at JKang.IpcServiceFramework.Hosting.NamedPipe.NamedPipeIpcEndpoint`1.WaitAndProcessAsync(Func`3 process, CancellationToken cancellationToken) --- End of inner exception stack trace ---`
> ![image](https://user-images.githubusercontent.com/45855057/91090810-5411fa00-e65e-11ea-8c16-4f20a8859f08.png)

#243
