### ISSUE TITLE
Upgrade to IpcServiceFramework 3.0.5

### ISSUE THREAD

**Issue by Mrcubix** [InfinityGhost/OpenTabletDriver#243]
## Description
This error get spammed in the console, causing high CPU usage, but also prevent the UI from connecting to the daemon
I've tried reinstalling the OTD driver from scratch, OEM drivers are killed, only 1 instance of OTD is started

![rarewindowsspampogu](https://user-images.githubusercontent.com/39861216/89221674-f6950b00-d5d3-11ea-9829-e92fb8238e32.PNG)

https://pastebin.com/Y9UHKTCu

## System Information:

Option            | Value
------------------|------------------
Operating System  | Win 8.1 64x
Software Version  | ALL
Tablet            | Gaomon 620 (in my case)

**Comment by InfinityGhost** [comment]
This may depend on https://github.com/jacqueskang/IpcServiceFramework/pull/156 being merged, along with a NuGet package update in order to fix.

**Comment by InfinityGhost** [comment]
Now we're waiting on v3.0.5 of IpcServiceFramework to be released, which is currently in preview on NuGet.

**Comment by Airkek** [comment]
![image](https://user-images.githubusercontent.com/45855057/91094481-82de9f00-e663-11ea-94ac-bb54b6af0f33.png)
Updating IpcServiceFramework to 3.0.5-preview helped

**Comment by JaaceB** [comment]
Could someone pls tell me how to update to IpsFramework 3.0.5? I just cant get it working

**Comment by Mrcubix** [comment]
> Could someone pls tell me how to update to IpsFramework 3.0.5? I just cant get it working

Replace the dll in OTD folder by this one : https://cdn.discordapp.com/attachments/615611007951306863/751201377249919036/JKang.IpcServiceFramework.Hosting.NamedPipe.dll

if the error still persist, then reboot your pc

**Comment by JaaceB** [comment]
Now it says: Failed to open tablet. Make sure you have required permissions to open device streams.

**Comment by Mrcubix** [comment]
> Now it says: Failed to open tablet. Make sure you have required permissions to open device streams.

i would suggest you come to the official discord server https://discord.gg/P3GYdUS we'll continue the discussion there
