### ISSUE TITLE
Cannot interact with Align and Resize menus

### ISSUE THREAD

**Issue by poopsey** [InfinityGhost/OpenTabletDriver#249]
When you right-click on the tablet area or display area the align and resize menus don't work.

[example video](https://cdn.discordapp.com/attachments/615611007951306863/740923418358317168/2020-08-06_22-58-06-00.00.04.166-00.00.08.333.mp4)

**Comment by InfinityGhost** [comment]
This is a bug on Windows' side, which there is no workaround for. All I can suggest is trying to click the box beforehand.
