### ISSUE TITLE
CTH-670 Bindings broken

### ISSUE THREAD

**Issue by acclaiming** [InfinityGhost/OpenTabletDriver#250]
## Description

Tablet Tip binding doesn't work at all, binding the side buttons to backslash (Windows layout set to US-ANSI) outputs "["

Not sure if the "Filters" and "Tools" tabs are supposed to be empty

Raw Input in osu! doesn't work at all.

Operating System  |  Windows 10 Pro Version 2004
Software Version  | 0.3.2
Tablet            | Wacom CTH-670

**Comment by acclaiming** [comment]
Just retested on Manjaro-XFCE: Pen tip works but I can't rebind any keys

**Comment by ssccoonniicc** [comment]
> Not sure if the "Filters" and "Tools" tabs are supposed to be empty

Those tabs are empty because no plugins are installed.

> Raw Input in osu! doesn't work at all.

With the way OpenTabletDriver works right now raw input will not work

> Tablet Tip binding doesn't work at all, binding the side buttons to backslash (Windows layout set to US-ANSI) outputs "["

That might be a problem with the config

>  Edit2: it's not detecting the tablet even though I followed the guide in the linux faq, IDK what to do anymore, it worked for a 
second in the beginning but now I'm stumped

Make sure to blacklist the wacom module but if that doesn't work then you can join the discord server for some extra help: https://discord.gg/P3GYdUS

**Comment by acclaiming** [comment]
Manjaro issues now fixed: the tablet tip and side button binding works absolutely perfectly on linux

![Screenshot_2020-08-08_18-20-37](https://user-images.githubusercontent.com/40470862/89715145-2b260f80-d9a4-11ea-9160-feb464aa8d0b.png)

**Comment by X9VoiD** [comment]
Support for Windows RawInput just got merged recently, next release will have it.

**Comment by InfinityGhost** [comment]
Can we confirm if this is fixed at bcce99be919cb6e50131de437be7d139c880b322?

**Comment by InfinityGhost** [comment]
Assuming fixed due to inactivity.
