### ISSUE TITLE
Windows x86 Support

### ISSUE THREAD

**Issue by EutMeHardPlz** [InfinityGhost/OpenTabletDriver#280]
Please add 32bit installer, my laptop says its for 64bit arch

**Comment by InfinityGhost** [comment]
Windows x86 as a whole is completely untested, however we can try building OTD for x86 to see if it works out of the box.

**Comment by InfinityGhost** [comment]
Compiling for win-x86 appears to work no problem, but I only tested it on a x64 platform. I don't intend on supporting x86 anyway, but I'll provide build instructions here
# Building for Windows x86 (32-bit)
- Install [git](https://git-scm.com/)
- Install [.NET 5 SDK](https://dotnet.microsoft.com/download/dotnet/5.0)
- Run the following commands in PowerShell
```ps
git clone https://github.com/InfinityGhost/OpenTabletDriver src
mkdir OpenTabletDriver
cd src
Copy-Item -Recurse .\TabletDriverLib\Configurations ..\OpenTabletDriver\Configurations
dotnet publish -f net5 -r win-x86 -o ..\OpenTabletDriver
```
- You can now run `OpenTabletDriver.UX.Wpf.exe` in the OpenTabletDriver directory that was created. It should launch the daemon as well.

**Comment by oDruvee** [comment]
I tried running the commands in the GIT Powershell and when I get to the Copy Item it says Copy Item: command not found

**Comment by InfinityGhost** [comment]
Let me see if I can make you up a binary myself

**Comment by InfinityGhost** [comment]
[OpenTabletDriver win-x86.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5686758/OpenTabletDriver.win-x86.zip)
This was built on the v0.4.2 tag

**Comment by oDruvee** [comment]
Ok, Thanks alot!

**Comment by oDruvee** [comment]
How can I get it to bypass my Avast Antivirus?

**Comment by InfinityGhost** [comment]
That's something you'll have to figure out with Avast. Most likely an antivirus exclusion.

**Comment by oDruvee** [comment]
I'm sorry if I'm giving you trouble but I have a Gaomon S620 an it's not detecting the tablet, what can I do?

**Comment by InfinityGhost** [comment]
From the OpenTabletDriver Discord
![image](https://user-images.githubusercontent.com/39218853/102047030-8892f880-3daa-11eb-949b-564822e67727.png)
