### ISSUE TITLE
Duplicate references to loaded plugins

### ISSUE THREAD

**Issue by X9VoiD** [InfinityGhost/OpenTabletDriver#285]
## Description
This issue causes multiple references to IOutputMode, IFilter, and ITool but only in rare cases. If it happens to a certain plugin then it will always happen to that certain plugin.

A workaround for IFilter duplicates have been made on #212

## System Information:

Option            | Value
------------------|------------------
Operating System  |  Windows

**Comment by InfinityGhost** [comment]
This also applies to ITool duplicates, this should only affect IOutputMode at this point.

**Comment by X9VoiD** [comment]
Closing this issue as it can't be reproduced anymore.
