### ISSUE TITLE
Driver can't connect to Daemon

### ISSUE THREAD

**Issue by Nyarogami** [InfinityGhost/OpenTabletDriver#289]
## Description
When the driver starts, it say's Connecting to OpenTabletDriver Daemon, but after a few minutes it's just closes.

## System Information:
Operating System  Windows 10 64bit 1809
Software Version    0.3.2
Tablet                     Gaomon s620

**Comment by AbstractQbit** [comment]
Try using recent builds from github.com/InfinityGhost/OpenTabletDriver/actions

**Comment by Mrcubix** [comment]
What happen is simple, either you started the daemon first and it spammed error and caused the UX to not work, or you just haven't started the daemon first

**Comment by Nyarogami** [comment]
I can connect to Daemon on 0.3.0, but still can't connect to Daemon on versions: 0.3.2 and 0.3.1.

**Comment by Mrcubix** [comment]
come on the official discord server, we will try to fix a fix to your issue there https://discord.gg/P3GYdUS

**Comment by Nyarogami** [comment]
Joined

**Comment by Mrcubix** [comment]
need to be closed

**Comment by InfinityGhost** [comment]
Issue already resolved in master branch
