### ISSUE TITLE
Gaomon s620 Not working

### ISSUE THREAD

**Issue by Extrallian** [InfinityGhost/OpenTabletDriver#294]
I can't change any settings.

**Comment by X9VoiD** [comment]
Please provide more information.

OS:
OTD Version:

and OTD -> Help -> Export Diagnostics

**Comment by Extrallian** [comment]
I am on Windows 10 OTD v 0.3.2
https://www.dropbox.com/s/n3drx7f590tfde5/diagnostic.json?dl=0

**Comment by X9VoiD** [comment]
Use the latest build from [dev-builds](https://github.com/InfinityGhost/OpenTabletDriver/actions)

**Comment by Extrallian** [comment]
Thank you

**Comment by InfinityGhost** [comment]
I assume this is resolved then?

**Comment by Mrcubix** [comment]
time to close that issue
