### ISSUE TITLE
Add estimated tablet report rate (report/second) to tablet debugger

### ISSUE THREAD

**Issue by AuracleTech** [InfinityGhost/OpenTabletDriver#303]
Here's the deal

I have a Wacom Intuos (CTL-4100)
I was messing with Hawku driver commands in console

And I found out that pen report increase drastically when the tip is pressured, which would be very usefull for the game Osu where the pen almost never touches the tablet and needs as much updates as possible.

Here's quick gifs I made to communicate. (Mouse reports / very small distance)

Pen tip not pressed, hovering and drawing a circle
![Hover Not presssed](https://user-images.githubusercontent.com/40531871/93536380-dcf71b00-f916-11ea-9702-0dd05e1a00bb.gif)

Pen tip pressed, hovering and drawing a circle
![Hover Pressed](https://user-images.githubusercontent.com/40531871/93536487-162f8b00-f917-11ea-9ed7-2b54b260e37c.gif)

And even tho I went less fast with the pen tip pressed test, you can see there's still way more reports, if I had a better test setup this would be even more drastic.

Is there a way you could add in the tablet debugger a reports/sec to be able to understand what is going on?

I think Wacom did this because when you hover the pen it's useless to send too much data, except we play Osu with these.

**Comment by InfinityGhost** [comment]
Adding a report rate display is a great idea, will work on it for v0.4.1 because I've already finalized everything for v0.4.0's release.
