### ISSUE TITLE
XP-Pen Deco 01 V2 not detected

### ISSUE THREAD

**Issue by drunkfromcoffee** [InfinityGhost/OpenTabletDriver#308]
## Description

My tablet isn't detected by OpenTabletDriver. I suspect it's not from OpenTablet's end, as I heard XP-Pen sometime changes it's product's id or something, but I'd very much like to be able to use this driver, since I also use Arch on another setup.

## System Information:

Option            | Value
------------------|------------------
Operating System  | Windows 10
Software Version  | 0.4.0
Tablet            | XP-Pen Deco 01 V2

https://hastebin.com/uhijoliwox.cs
https://andrein.is-inside.me/BxEBHfk5.json

**Comment by drunkfromcoffee** [comment]
Looked at the json I sent, apparently the Product ID is 2309 for me, compared to the 2306 from the config. Even if I configured the proper Product ID though, it still doesn't detect it.

**Comment by Mrcubix** [comment]
you might want to join the discord server and #help-windows channel https://discord.gg/P3GYdUS

**Comment by X9VoiD** [comment]
Open `Configurations/XP-Pen/Deco 01 v2.json` then change ProductID from 2306 to 2309 as you've discovered. Save then restart daemon and ux

**Comment by X9VoiD** [comment]
As Mrcubix have said, join our discord server for further assistance: https://discord.gg/P3GYdUS

**Comment by InfinityGhost** [comment]
Is this resolved?

**Comment by InfinityGhost** [comment]
This issue seems dead. Assuming it has been resolved since.
