### ISSUE TITLE
Huion H430P - not detected

### ISSUE THREAD

**Issue by LittleWhole** [InfinityGhost/OpenTabletDriver#310]
## Description

The Huion H430P tablet is not detected by OpenTabletDriver. It detects my XP-Pen G430S just fine.

I saw that in the Projects > Tablet Support, The Huion H430P is listed as "untested". I've used the XP-Pen G430S just fine with OpenTabletDriver, however my Huion H430P is not being detected by OpenTabletDriver no matter what I do. I can confirm it's not a tablet issue as it works fine with other devices.

## System Information:

Option            | Value
------------------|------------------
Operating System  | Pop!_OS 20.04 LTS
Software Version  | v0.4.0
Tablet            | Huion H430P

**Comment by X9VoiD** [comment]
Open `Configurations/Huion/H430P.json` then change ProductID from 110 to 109, then restart daemon and ux

**Comment by LittleWhole** [comment]
Sadly doesn't seem to be working

**Comment by X9VoiD** [comment]
Join Discord server so we could help you: https://discord.gg/P3GYdUS
