### ISSUE TITLE
Simpler selection of which monitor the tablet will map to.

### ISSUE THREAD

**Issue by solonovamax** [InfinityGhost/OpenTabletDriver#311]
## Description
Allow users to select monitors rather than having to fine-tune the display area settings.

## Example implementation:
For me, I have 3 monitors and finding the correct X Offset took a bit of fiddling because it seems that the offsets aren't relative to the top right corner.
Instead, it would show a dropdown box with where you can select "Custom" or "Monitor". Under "Custom", it will show the configuration for the display area. Under "Monitor", it will show a dropdown box with a list of all your screens (and an additional "all screens") + a display preview for the one you selected. (see attached for example.)
There would also be lines drawn from an example image of a tablet onto the screen to show how it would be mapped to the screen.

### Single monitor
![image](https://user-images.githubusercontent.com/46940694/93833646-34fb8d80-fc47-11ea-9c17-72cf96a2a285.png)
### All monitors
![image](https://user-images.githubusercontent.com/46940694/93832892-14cacf00-fc45-11ea-8cca-71267db72abc.png)
### Full window
![image](https://user-images.githubusercontent.com/46940694/93835482-64ad9400-fc4d-11ea-99af-431c91e2c753.png)
(why did I spend 3 hours making this)

#### Notes
- The drop-down menus are all expanded only to show you what would be in each one.
- In my specific configuration I have a 1680×1050 monitor as my left-most monitor, the rest are 1080p.
- The screen names here are not tied directly to the X monitor names, they are sorted based on their position.
- The coordinates shown in the picture are the top-left coordinates to the bottom right coordinates of the X monitor
- Even though my 1st monitor is 1680×1050, I still stretched the screen size in the display, as it is roughly the same physical size. (Where the pen appears should be proportional to physical monitor size rather than display size as that makes more sense when using it. Though, then x coordinate on the tablet will already be more or less multiplied by 3, so it isn't exactly the easiest to use.)

**Comment by X9VoiD** [comment]
Right clicking on display area will provide you an option to set to specific monitors

**Comment by solonovamax** [comment]
Oh, I'm just braindead.

Would be nice to have a preview for it though because  f a n c y

**Comment by solonovamax** [comment]
Also, I'd like to add on that a keybind to cycle through which monitor its bound to might be nice for working with multimonitor setups. (rather than having to go to your mouse for a simple task, you can use the tablet)
Alternatively, you could add a keybind to go left/right in your monitor selection.

(Don't feel like making a new issue for this since these are kind of related.)

**Comment by X9VoiD** [comment]
This kind of functionality is not essential, nor in high demand, so if ever this feature will be implemented, it will be as a plugin. Not as a core part of OTD. The issue may be closed now

**Comment by solonovamax** [comment]
Fair
