### ISSUE TITLE
Tablet Driver closing when clicking start

### ISSUE THREAD

**Issue by snowl** [InfinityGhost/OpenTabletDriver#315]
## Description

I tried installing 0.4.0 today and whenever I open the driver installer and click start it just closes and re-opens the driver. I can't find any log to attach either to help debug.

## System Information:

Option            | Value
------------------|------------------
Operating System  |  Windows 10 x64
Software Version  |    0.4.0
Tablet            |           Gaomon S620

**Comment by InfinityGhost** [comment]
Install the .NET Core 3.1 runtime
https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-3.1.8-windows-x64-installer
