### ISSUE TITLE
Nothing happens when clicking "start" in the updater window. 

### ISSUE THREAD

**Issue by captainshrimps** [InfinityGhost/OpenTabletDriver#326]
## Description

I installed the driver using the windows auto-updater and it installs successfully but when I click start all that happens is the updater window disappears for a moment then re-opens. Nothing else happens and I can't use my tablet. 
![opentabletdriver updater](https://user-images.githubusercontent.com/71992021/94378313-15b5a200-0118-11eb-8901-0818f4fcbbb5.PNG)

## System Information:

Option            | Value
------------------|------------------
Operating System  | Windows 10
Software Version  | 0.4.0
Tablet            | XP-PEN G430S

**Comment by X9VoiD** [comment]
Install .NET Core runtime

**Comment by captainshrimps** [comment]
> 
> 
> Install .NET Core runtime

Thank you, this solved the issue.
