### ISSUE TITLE
No tablet detected with HUION HS64

### ISSUE THREAD

**Issue by zMici** [InfinityGhost/OpenTabletDriver#334]
## Description

The drivers aren't detecting my tablet,

## System Information:

Option            | Value
------------------|------------------
Operating System  |    
![Untitled](https://user-images.githubusercontent.com/57213669/94621372-cbb7f200-02b8-11eb-80a2-b9fad20a379a.png)
Windows 10
Software Version  |    0.4.0
Tablet            |    Huion HS64

**Comment by Mrcubix** [comment]
make sure all other driver are uninstalled like vmulti, huion driver, also, uninstall winusb in programs if not already done, finally, go into device manager, delete "huion tablet" and "Graphic Tablet Device", reboot and it should be detected,

**Comment by zMici** [comment]
Thank you, I guess I had vmulti still installed. works perfectly now.
