### ISSUE TITLE
[Windows] Wrong input mapping when monitors are unaligned

### ISSUE THREAD

**Issue by X9VoiD** [InfinityGhost/OpenTabletDriver#336]
## Description
When the monitors are not aligned in a specific axis, OTD's input behaves incorrectly. It tries to scale from the lowest value of that axis to the highest without regards to where the monitors end in that axis. 

## System Information:
Option            | Value
------------------|------------------
Operating System  |  Windows

**Comment by X9VoiD** [comment]
This is an image for example.

![unknown](https://user-images.githubusercontent.com/10338031/94632908-61c23b80-02fe-11eb-9d1d-c3bf47773499.png)

The cursor won't be able to reach the bottom part of the mapped monitor area by the same scaled amount of misalignment in Y axis

**Comment by InfinityGhost** [comment]
Unable to reproduce this as of right now

**Comment by X9VoiD** [comment]
Closing this issue
