### ISSUE TITLE
How to make this work on Gaomon S620?

### ISSUE THREAD

**Issue by UltimateKaren** [InfinityGhost/OpenTabletDriver#341]
Hello! I know this isn't an issue but I couldn't find anything in the FAQ that helped me. I use a gaomon s620 and downloaded and extracted everything in OpenTabletDriver.win-x64. I ran OpenTabletDriver.Daemon.exe and OpenTabletDriver.UX.Wpf.exe and it hasn't detected my tablet and isn't showing any settings. Here are some screenshots
Edit: also, every time I try to minimize the tab it just closes the program and makes me run the exe again. Is that normal? Is it just the Gaomon drivers that don't do that?
I'm bad with computers in general and if someone could help out that would be greatly appreciated :"D

![image](https://user-images.githubusercontent.com/65194640/94876168-b9020200-040b-11eb-9361-599bc03fceeb.png)
![image](https://user-images.githubusercontent.com/65194640/94876229-e9e23700-040b-11eb-809a-abc68da6dbab.png)

Edit again: Here's what it looks like now. I can't get the tablet detected and the program still closes every time I minimize it and I have to re-run the whole thing.
![image](https://user-images.githubusercontent.com/65194640/94876583-edc28900-040c-11eb-97b0-998447c37e74.png)

**Comment by X9VoiD** [comment]
1. Open Device Manager
2. View -> Devices by Connection
3. Find Gaomon HID / Graphics Tablet Device in USB controllers
4. Right Click -> Uninstall Device (tick the checkbox that says "Delete driver files")
5. Replug tablet
6. Open OTD

If still not working, join the discord server: https://discord.gg/P3GYdUS

**Comment by InfinityGhost** [comment]
Issue appears to be stale, no update after 1 week and this will be closed.

**Comment by bossdragonde** [comment]
Thanks this fixed my problem.

**Comment by InfinityGhost** [comment]
Added this to the [Windows FAQ](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Windows-FAQ#my-gaomonhuion-tablet-isnt-detected-but-is-listed-as-supported)
