### ISSUE TITLE
Invalid Area in settings.json

### ISSUE THREAD

**Issue by X9VoiD** [InfinityGhost/OpenTabletDriver#359]
## Description
OTD produces an invalid area configuration on settings.json in cases where there is no tablet to be found, but the "save" button is pressed.

**Comment by InfinityGhost** [comment]
What are the side effects of an area being the incorrect size? What could we do for default values instead?

**Comment by X9VoiD** [comment]
What happens is that it saves a zero width, zero height rectangle area to the settings.json. What we could do is to block saving a settings.json when the area will result to <NaN, NaN>, or simply when there is no tablet.

**Comment by InfinityGhost** [comment]
Unable to reproduce this as of 110cdb181fc895f749d4f780f377c6eeeadcbdeb

**Comment by InfinityGhost** [comment]
Reproduced the NaN position by dragging on an area with 0 width & 0 height
