### ISSUE TITLE
Failing dotnet build commands under Linux-FAQ

### ISSUE THREAD

**Issue by ceilingwaffle** [InfinityGhost/OpenTabletDriver#363]
## Description
https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ

./build.sh was failing with error:
![image](https://user-images.githubusercontent.com/25700760/95859453-60871900-0daa-11eb-9e6a-88244eeeb185.png)
(new setup sorry, unable to copy and paste from terminal)

Updated the wiki here with working commands (not sure how to submit pull requests for wiki pages)
https://github.com/ceilingwaffle/OpenTabletDriver/wiki/Linux-FAQ

```bash
git clone https://github.com/InfinityGhost/OpenTabletDriver-udev.git
cd OpenTabletDriver-udev
git clone https://github.com/InfinityGhost/OpenTabletDriver.git ./.modules/OpenTabletDriver
mkdir ./build
./build.sh
sudo mv ./build/30-opentabletdriver.rules /etc/udev/rules.d/30-opentabletdriver.rules
sudo udevadm control --reload-rules
cd ..
rm -rf OpenTabletDriver-udev
```

**Comment by X9VoiD** [comment]
Should instead initialize the git submodule.

```git submodule update --init --remote```

**Comment by InfinityGhost** [comment]
Updated the wiki to match the submodule update requirement.
