### ISSUE TITLE
tablet area issue

### ISSUE THREAD

**Issue by Au-xx** [InfinityGhost/OpenTabletDriver#376]
## Description

I set the screen to my monitor and set a tablet area. Instead it used the whole tablet and only used half of the screen.

## System Information:

Option            | Value
------------------|------------------
Operating System  | Windows 10
Software Version  | Latest
Tablet            |  XP-PEN G640

**Comment by InfinityGhost** [comment]
This is fixed in the master branch, use a development build: https://github.com/InfinityGhost/OpenTabletDriver/actions/runs/305792363

**Comment by Au-xx** [comment]
im stupid dw

**Comment by Au-xx** [comment]
i kinddaaa forgot to press apply im sooooo dumb
