### ISSUE TITLE
More button features

### ISSUE THREAD

**Issue by The-Mach34** [InfinityGhost/OpenTabletDriver#380]
I am wondering if you could add some more button options and features. For example, I would like to be able to open osu! with one of the buttons on my tablet or do commands like ctrl + shift + t with pen buttons or something. I know that many of the default drivers for tablets have these functions and I found it useful when I was using the default Gaomon divers but because they are bad I downloaded these but wished that I could bind the buttons so they are not completely wasted unless I want to do a very basic function with them.

**Comment by Mrcubix** [comment]
basically duplicate of https://github.com/InfinityGhost/OpenTabletDriverPlugins/issues/6

**Comment by skyborgff** [comment]
The next release of VoiDPlugins https://github.com/X9VoiD/VoiDPlugins will have the ability to assign a executable / program / file to a button, allowing you to run a AutoHotkey script to run any  command you like

**Comment by Mrcubix** [comment]
built today by skyborg https://cdn.discordapp.com/attachments/628651971267788800/766729148898607124/ScriptRunner.dll enjoy

**Comment by The-Mach34** [comment]
Cool, thanks.
