### ISSUE TITLE
DECO 03 Support

### ISSUE THREAD

**Issue by Gitkubikon** [InfinityGhost/OpenTabletDriver#381]
Hello!!
I have a DECO 03 and since Xp-Pen can't provide good enough drivers, I'd be very graceful if u could support it sooner or later :)
Thanks in advance !!

**Comment by X9VoiD** [comment]
Open OTD, then OTD -> Help -> Export Diagnostics

Upload the generated file here

**Comment by Gitkubikon** [comment]
[Deco 03 Diagnostics.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5395522/Deco.03.Diagnostics.txt)

**Comment by X9VoiD** [comment]
Not sure what's up with your system but the diagnostics failed to retrieve MaxInputReportLength and MaxOutputReportLength, try running daemon as sudo then export diagnostics again

**Comment by Gitkubikon** [comment]
Done, I ran it as root

X9VoiD <notifications@github.com> schrieb am Sa., 17. Okt. 2020, 13:40:

**Comment by X9VoiD** [comment]
[Deco 03.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5396130/Deco.03.zip)
Extract zip content, then put it into `Configurations/XP-Pen/Deco 03.json`. Now it might or might not work depending on the initialization needed for the Deco 03, but if it did work, then do the following:

1. Open OTD -> Tablet -> Tablet Debugger
2. Hover your pen to the bottom right most part of the physical tablet, and try to get the maximum value for `Position`
3. Determine the `Report ID` when hovering and not hovering
4. Press your pen until you get max `Pressure`
5. Report back here the `Position`, the max `Pressure`, and the active and inactive `ReportIDs`

**Comment by X9VoiD** [comment]
Oh, uh... This configuration format is compatible only on the latest dev build, download it from [here.](https://github.com/InfinityGhost/OpenTabletDriver/actions/runs/309900189)

**Comment by Gitkubikon** [comment]
It didn't work, it gave me an error in the console :

DeviceIOException        Unable to open HID class device (OK).

**Comment by X9VoiD** [comment]
[Deco 03.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5396364/Deco.03.zip)

**Comment by Gitkubikon** [comment]
![pic-selected-201017-2117-00](https://user-images.githubusercontent.com/57829844/96351804-37be9680-10be-11eb-8dfe-c4549d1afba7.png)

**Comment by Gitkubikon** [comment]
![pic-full-201017-2117-11](https://user-images.githubusercontent.com/57829844/96351808-47d67600-10be-11eb-88c4-6354fc3d76b2.png)

**Comment by X9VoiD** [comment]
Join the (discord server)[https://discord.gg/P3GYdUS], DECO 03 might need a different initialization than what's currently known for XP-Pen tablets

**Comment by InfinityGhost** [comment]
#387 merged and wasn't linked to this, closing this issue now.
