### ISSUE TITLE
Gaomon S620 Driver issues

### ISSUE THREAD

**Issue by Manson-22** [InfinityGhost/OpenTabletDriver#403]
drivers dont work with Gaomon S620. 
![image](https://user-images.githubusercontent.com/69829336/97251924-12204400-17c6-11eb-93af-3c3f87778a03.png)
![image](https://user-images.githubusercontent.com/69829336/97251940-19475200-17c6-11eb-80ef-5c2b3b6b069d.png)

**Comment by ssccoonniicc** [comment]
Do the following steps:
Device Manager -> View -> Devices by Connection
Find for any of these devices inside usb controllers:
  -  Gaomon HID
  -  Huion HID
  -  Graphics Tablet Device
  -  HID Tablet

Uninstall them (and check delete driver files) then replug tablet

**Comment by Manson-22** [comment]
thanks, im not really the best with drivers, as I only know some basic info on the original hawku drivers, and I just got a new tablet.f

**Comment by Manson-22** [comment]
never mind. it says invalid area size.

**Comment by ssccoonniicc** [comment]
can you share a screenshot of the driver

**Comment by InfinityGhost** [comment]
If you get that, reset to default settings, or change width and height to something bigger than 0 and set the position value to be a valid number

**Comment by InfinityGhost** [comment]
Any update on this?

**Comment by InfinityGhost** [comment]
Assuming this is resolved because of no response in over 7 days.
