### ISSUE TITLE
Does not work with Gaomon S620

### ISSUE THREAD

**Issue by raf060708** [InfinityGhost/OpenTabletDriver#405]
## Description

Tablet is not detected

## System Information:

Option            | Value
------------------|------------------
Operating System  | Windows 10
Software Version  |Latest
Tablet            | Gaomon S620

**Comment by raf060708** [comment]
![daf](https://user-images.githubusercontent.com/73594127/97438783-d9b06f80-1957-11eb-8313-1550231c64c1.PNG)

**Comment by raf060708** [comment]
Already tried deleting Gaomon HID in device manager but it still doesn't work

**Comment by X9VoiD** [comment]
Make sure you deleted the driver files when prompted, and also searched under **USB Controllers** for the device. When you're sure that they're gone, replug tablet, then restart OTD.

**Comment by raf060708** [comment]
![daf](https://user-images.githubusercontent.com/73594127/97440910-ae7b4f80-195a-11eb-92d2-70e90abbc25b.PNG)
which one should I delete?

**Comment by raf060708** [comment]
Sorry I am shit at this

**Comment by X9VoiD** [comment]
Make sure you are using the correct view: `View -> Devices by Connection`

**Comment by raf060708** [comment]
Which one should I delete
![Capture](https://user-images.githubusercontent.com/73594127/97441757-a53eb280-195b-11eb-8edb-01bc792baf3a.PNG)

**Comment by X9VoiD** [comment]
Follow the FAQ instructions. Open ACPI x64, find the USB controllers, then recursively search for the Gaomon HID, or whatever you'll find. Please don't ask step-by-step.

**Comment by raf060708** [comment]
Deleted Gaomon tablet, It's all I could find and Tablet is still not detected

**Comment by Mrcubix** [comment]
just replug your tablet now that you uninstalled AND removed the driver

**Comment by raf060708** [comment]
Already did that and it still says that No Tablet detected

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, send the file here

**Comment by Mrcubix** [comment]
also "Gaomon Tablet" might be there instead of "Gaomon HID" or just "HID Pen" because you might still have gaomon driver installed

**Comment by raf060708** [comment]
[HEELEPME.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5452259/HEELEPME.txt)

**Comment by X9VoiD** [comment]
According to the diagnostics, you still haven't done the instructions from FAQ correctly. Make sure you've uninstalled the Gaomon OEM Driver, and then perform the FAQ fix again, then restart OTD.

**Comment by Mrcubix** [comment]
you still have gaomon driver installed, just confirmed by me now by installing the driver and checking my devices

**Comment by raf060708** [comment]
Im fukcing dumb

**Comment by raf060708** [comment]
![image](https://user-images.githubusercontent.com/73594127/97446996-aa9efb80-1961-11eb-822b-75a1a838588e.png)
i swear there is nothing

**Comment by Mrcubix** [comment]
![gaomon tablet](https://user-images.githubusercontent.com/39861216/97447587-fdf85600-192f-11eb-800f-512e6c861b87.PNG)

**Comment by Mrcubix** [comment]
uninstall both of these is what i meant

**Comment by raf060708** [comment]
okk

**Comment by raf060708** [comment]
When I try to delete the second one this appears
![Capture](https://user-images.githubusercontent.com/73594127/97480976-b94bd980-1986-11eb-8b16-54cd05f1fd29.PNG)

**Comment by Mrcubix** [comment]
reinstall gaomon driver, uninstall winusb first gaomon after

**Comment by raf060708** [comment]
ok thx

**Comment by raf060708** [comment]
Did all the steps but it still says no tablet detected

**Comment by Mrcubix** [comment]
just to make sure, you uninstalled winUSB and gaomon drivers, you uninstalled vmulti if you ever installed it, you removed Gaomon HID in your devices with the following steps: 
- View > by connection
- search for the usb controller in ACPI x64, an look for Gaomon HID or Gaomon tablet

**Comment by raf060708** [comment]
how do you  uninstall vmulti

**Comment by Mrcubix** [comment]
in the UX: Help > export diagnostic and send it

**Comment by raf060708** [comment]
[OpenTabletDriver.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5458660/OpenTabletDriver.txt)

**Comment by raf060708** [comment]
Sorry it took a long time, Just woke up

**Comment by raf060708** [comment]
?

**Comment by raf060708** [comment]
hwlp

**Comment by X9VoiD** [comment]
Join discord server for further hwlp: https://discord.gg/P3GYdUS

**Comment by InfinityGhost** [comment]
Assuming this is resolved.
