### ISSUE TITLE
Support for Wacom CTE-460 Tablet

### ISSUE THREAD

**Issue by cl20103B11** [InfinityGhost/OpenTabletDriver#407]
I only have this very old tablet :c

**Comment by skyborgff** [comment]
Open OTD
Help -> export diagnostics and upload here

**Comment by cl20103B11** [comment]
[diagnostics.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5458449/diagnostics.txt)

**Comment by skyborgff** [comment]
tablet -> open configuration editor -> generate new configuration -> select your tablet. Do tell if it works btw

**Comment by X9VoiD** [comment]
OTD in this case won't be able to properly generate a correct configuration since it had no access to report length information. Run both OTD Daemon and UX as sudo, and then export diagnostics again.

**Comment by cl20103B11** [comment]
[test.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5463383/test.txt)

"Running as root and export diagnostics"

**Comment by X9VoiD** [comment]
Use latest [dev build](https://github.com/InfinityGhost/OpenTabletDriver/actions/runs/336984458) (sign in to access download links) then download the zip below
> [CTE-460.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5465148/CTE-460.zip)

Extract content to `Configuration\Wacom`, please do note that the config contains dummy values for tablet dimensions and is only for the purpose of getting the tablet detected in OTD. The dimensions and specs will be updated later.

> [30-opentabletdriver.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5465194/30-opentabletdriver.zip)

Extract content to `/etc/udev/rules.d/`, then run `sudo udevadm control --reload-rules && sudo udevadm trigger`

**Comment by X9VoiD** [comment]
Any news on this?

**Comment by InfinityGhost** [comment]
@cl20103B11

**Comment by cl20103B11** [comment]
Sorry for the late cuz too busy :c , It works, thx

**Comment by X9VoiD** [comment]
Now that it's working, we should confirm the specs of the tablet.

Open OTD -> Tablet -> Tablet Debugger, then hover your pen slowly to bottom right most part of the tablet. Try to get the highest possible `Position` you can get.

And then check what `ReportID` it says when hovering pen, and when pen is out of range.

Lastly, check the maximum `Pressure` of the pen.

**Comment by X9VoiD** [comment]
@cl20103B11 any news on the three values?

**Comment by cl20103B11** [comment]
sorry I m too busy to do other stuff and I finally release myself. Idk why it can't detect my tablet now, when I look the console it say SetFeature failed

**Comment by InfinityGhost** [comment]
Gotta love when someone just is like "woot it works" and ignores the entire issue after the fact. Assume the values are correct and we'll patch later if need be.

**Comment by cl20103B11** [comment]
sorry about the late, I am too busy on study and finally finished all of the work recently. Highest Possible Position I get is (14760, 9225), ReportID is 72 and 64 when the cursor touch the edge, maximum pressure is 1023. 

Really sorry about very late reply orz

**Comment by AbstractQbit** [comment]
Hmm, odd value of max Y coord looks a bit strange. Just to double-check, instead of trying to get both maxed out at once, can you try getting max values separately, first max X on the right edge and then max Y at the bottom edge of the tablet?

**Comment by cl20103B11** [comment]
> Hmm, odd value of max Y coord looks a bit strange. Just to double-check, instead of trying to get both maxed out at once, can you try getting max values separately, first max X on the right edge and then max Y at the bottom edge of the tablet?

still got max X:14760 Y:9225

**Comment by InfinityGhost** [comment]
Should have closed with #471, closing now.
