### ISSUE TITLE
GAOMON S620 Not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by DavidRamosSal** [InfinityGhost/OpenTabletDriver#408]
## Description

I installed the software following the guide for Ubuntu, but when I open the GUI I get "No tablet detected".
The "Console" tab gives the following error in the detection process:
 [ArgumentOutOfRangeException:Error]	Value range is [0, 15]. (Parameter 'value')
 
I ran the udev rules script found in the FAQ successfully, but the situation in the GUI hasn't changed and the tablet is not being recognized.

## System Information:

Option            | Value
------------------|------------------
Operating System  | Ubuntu 20.04.1
Software Version  | OpenTabletDriver v0.4.1
Tablet            | GAOMON S620

**Comment by X9VoiD** [comment]
Restart OTD Daemon

**Comment by InfinityGhost** [comment]
```sh
systemctl --user restart opentabletdriver.service
```

**Comment by robik65** [comment]
> systemctl --user restart opentabletdriver.service

Worked the at first, then I opened my pc the next day and the issue is till there and also this no longer works.
I am using the latest pop os build.

**Comment by DavidRamosSal** [comment]
> ```shell
> systemctl --user restart opentabletdriver.service
> ```

Thanks for the reply. It didn't change anything. I wonder if I should try to install from scratch.

**Comment by InfinityGhost** [comment]
Give reinstalling a try, and use `sudo apt install ./OpenTabletDriver.deb` to install it. Some apt frontends like gdebi don't properly install packages.

**Comment by robik65** [comment]
> Give reinstalling a try, and use `sudo apt install ./OpenTabletDriver.deb` to install it. Some apt frontends like gdebi don't properly install packages.

This didn't fix it for me.

**Comment by InfinityGhost** [comment]
Try the following commands, then replugging your tablet
```bash
echo 'KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess", OPTIONS+="static_node=uinput"' | sudo tee -a /etc/udev/rules.d/99-custom.rules
sudo udevadm control --reload-rules
systemctl --user restart opentabletdriver.service
```

**Comment by robik65** [comment]
> Try the following commands, then replugging your tablet
> 
> ```shell
> echo 'KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess", OPTIONS+="static_node=uinput"' | sudo tee -a /etc/udev/rules.d/99-custom.rules
> sudo udevadm control --reload-rules
> systemctl --user restart opentabletdriver.service
> ```
Didn't work either

**Comment by X9VoiD** [comment]
Make sure you've restarted OTD UX every time you restarted the OTD daemon. And just to be really sure:
```
sudo udevadm control --reload-rules && sudo udevadm trigger
```

**Comment by robik65** [comment]
> sudo udevadm control --reload-rules && sudo udevadm trigger

I dont understand, but I tried that aswell and didn't work.

I also tried everyting you all posted above again and nothing worked

**Comment by X9VoiD** [comment]
```
sudo rmmod hid_uclogic
sudo udevadm control --reload-rules && sudo udevadm trigger
systemctl --user restart opentabletdriver.service
```
then restart OTD UX

**Comment by robik65** [comment]
> ```
> sudo rmmod hid_uclogic
> sudo udevadm control --reload-rules && sudo udevadm trigger
> systemctl --user restart opentabletdriver.service
> ```
> 
> then restart OTD UX

This fixed the issue for now. Thank you! <3

**Comment by X9VoiD** [comment]
Restart your PC and see if the issue comes back.

**Comment by robik65** [comment]
> Restart your PC and see if the issue comes back.

It came back

**Comment by X9VoiD** [comment]
Run `lsmod` and see if hid_uclogic or wacom is loaded

**Comment by robik65** [comment]
There is no wacom in there, but hid_uclogic has 0

**Comment by X9VoiD** [comment]
Follow the [instructions here](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#permanently-disable-the-wacom-module
) and instead of `wacom`, blacklist `hid_uclogic`.

Delete `/etc/udev/rules.d/30-opentabletdriver.rules`

Then [download this zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5471471/rules.zip):

And extract it as `/etc/udev/rules.d/99-opentabletdriver.rules`

Finally, restart PC

**Comment by robik65** [comment]
> Follow the [instructions here](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#permanently-disable-the-wacom-module) and instead of `wacom`, blacklist `hid_uclogic`.
> 
> Delete `/etc/udev/rules.d/30-opentabletdriver.rules`
> 
> Then [download this zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5471471/rules.zip):
> 
> And extract it as `/etc/udev/rules.d/99-opentabletdriver.rules`
> 
> Finally, restart PC

After some trouble installing `dotnet-sdk`, at `./build.sh` the command returns this error 

_/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/robik65/OpenTabletDriver-udev/OpenTabletDriver.udev/OpenTabletDriver.udev.csproj]

The build failed. Fix the build errors and run again._

**Comment by X9VoiD** [comment]
Just follow the instructions for "Permanently disable the wacom module", nothing more

**Comment by robik65** [comment]
> Just follow the instructions 1 and 2 for "Permanently disable the wacom module", nothing more

Did that, it's fixed now. Thank you

**Comment by DavidRamosSal** [comment]
> Follow the [instructions here](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#permanently-disable-the-wacom-module) and instead of `wacom`, blacklist `hid_uclogic`.
> 
> Delete `/etc/udev/rules.d/30-opentabletdriver.rules`
> 
> Then [download this zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5471471/rules.zip):
> 
> And extract it as `/etc/udev/rules.d/99-opentabletdriver.rules`
> 
> Finally, restart PC

Disabling `hid_uclogic` worked for me too, thanks for the help! Will close now.
