### ISSUE TITLE
Support for custom key binds with Windows Ink mode plugin

### ISSUE THREAD

**Issue by sbstratos79** [InfinityGhost/OpenTabletDriver#415]
## Description

Windows Ink feature doesn't let the user use the key binds. I think the mode becomes almost useless without the keybinds. Having to scroll using a scrollbar or zoom in with Ctrl++ instead of Ctrl+Pan in a painting program is way too tedious.

**Comment by skyborgff** [comment]
That is a planned feature, for now you can use the script runner from VoidPlugins and AutoHotkey to have advanced multikey binding

**Comment by sbstratos79** [comment]
Is there a tutorial for scriptrunner and Autohotkey for setting custom keybinds? I only have a rudimentary understanding of these things.

**Comment by skyborgff** [comment]
AutoHotkey you will have to search yourself. For script runner just install the plugin like you did to windows ink, right-click the bingeing in OTD that you want to set, and select "Script Runner" in the first drop-down, and the script number in the second. In the tools tab put the path to the .AHK in the number "slot" you want

**Comment by sbstratos79** [comment]
I looked for Script Runner in the releases but couldn't find it. I downloaded the zip from Void Plugins master branch but the Script runner folder has cs and csproj files instead of dlls. I copied them to the Plugins folder but they aren't installed. Is there any way to install it?

**Comment by skyborgff** [comment]
Download from here as it won't be built until next release 

https://cdn.discordapp.com/attachments/628651971267788800/766729148898607124/ScriptRunner.dll

**Comment by sbstratos79** [comment]
Thanks! It's installed now.

**Comment by skyborgff** [comment]
Looking at #414 i misunderstood what you wanted. I thought you wanted multiple key hotkeys. That's not natively possible for now. One key binding is

**Comment by sbstratos79** [comment]
I actually meant both. Keybindings support as well as keybindings combinations support. Although I was partially mistaken on the keybindings support part. While Windows Ink does support key binds, it doesn't seem to support all. It doesn't support Right Click for example. I haven't tested enough to find out what other keys it doesn't support.

**Comment by skyborgff** [comment]
It doesn't because of a design decision that I don't agree with tbh. It "highjack" the 3 mouse buttons and maps them like if they were a pen. Left is click, right is the barrel button on a surface pen, and middle is eraser. You can not change this behaviour as it's hardcore's in the plugin. Giving that now I have a real case we're that is an issue, I'll try to talk them over changing it.

**Comment by skyborgff** [comment]
For the keybindings combination for now use AHK. It's planned to be natively supported tho

**Comment by sbstratos79** [comment]
Thanks. I am watching some AutoHotkey and AHKHID tutorials for enabling this. I'll check if it works with right click or not and report back.

**Comment by AbstractQbit** [comment]
That hijacking is needed because your windows ink pointer is not your mouse pointer, so clicking mouse buttons would click at the last mouse location, not where the tablet points to

**Comment by sbstratos79** [comment]
The AHK script works with Right Click.

**Comment by X9VoiD** [comment]
WindowsInk cursor is **not** the same as the mouse cursor as AbstractQBit have explained. Triggering the "normal" left, right, and middle click event while WindowsInk is active **will cause issues**.

We can easily just fix the "hijacking" by providing new `IBinding` dedicated to WindowsInk and LinuxArtistMode but that will cause issues when a user left the pen bindings as the "normal" left, right, middle clicks. They are just **not** available from the devices that both output modes emulate. It will also become really tedious when switching from one output mode to another, you must change the bindings constantly or OTD will crash (null reference).

And also, you can just press space then drag to move around the canvas on most painting programs (krita, photoshop, etc)

Hence why this is another `wontfix` issue and should be closed.

**Comment by X9VoiD** [comment]
A future change will come to address confusion for OTD's Left, Right and Middle binding's adaptive behaviour (which you guys call hijacking)

**Comment by InfinityGhost** [comment]
This is not focused on this repository and should be moved to the Windows Ink repository source (https://github.com/X9VoiD/VoiDPlugins)

**Comment by sbstratos79** [comment]
Alright. I'll open another issue in the other repository
