### ISSUE TITLE
Support Request: XP-PEN DECO 02

### ISSUE THREAD

**Issue by lmdfmh** [InfinityGhost/OpenTabletDriver#421]
After installing the linux driver (aur), it stops working, does not respond to movement and buttons.
 In the debug window, everything works fine, all buttons are recognized and movement too.
[XP-PEN DECO 02.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5489013/XP-PEN.DECO.02.txt)

**Comment by X9VoiD** [comment]
Check Tablet Debugger and see what ReportID it says during hover, and when pen is out of range

**Comment by lmdfmh** [comment]
while hover ReportID:80, when out of range ReportID:96 also pen have eraser on other side ReportID:84

**Comment by X9VoiD** [comment]
Hover on the bottom right most part of the physical tablet area and try to retrieve the highest possible value for `<Position>`

**Comment by lmdfmh** [comment]
22352, 13970

**Comment by X9VoiD** [comment]
Are you entirely sure now with those values? If yes, then

[Deco 02.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5489455/Deco.02.zip)

Extract zip contents to `Configurations\XP-Pen` then restart OTD

**Comment by lmdfmh** [comment]
i checked values 10 times. yes i'm sure.
did it but no changes, still work only in debug window:(

**Comment by X9VoiD** [comment]
Are you sure that you've replaced the config that is already in there? And restarted OTD? If yes then, 

[Deco 02.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5489553/Deco.02.zip)

**Comment by lmdfmh** [comment]
i checked values 10 times. yes i'm sure.
did it but no changes, still work only in debug window:(

**Comment by X9VoiD** [comment]
Restart PC

**Comment by lmdfmh** [comment]
i did. also replugged a tablet

**Comment by X9VoiD** [comment]
Export Diagnostics

**Comment by lmdfmh** [comment]
[deco02.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5489624/deco02.txt)

**Comment by X9VoiD** [comment]
```
sudo udevadm control --reload-rules && sudo udevadm trigger
systemctl --user restart opentabletdriver
```
and then start UX

**Comment by X9VoiD** [comment]
If still not working after that then, `stat /dev/uinput`

**Comment by lmdfmh** [comment]
[inzane@archlinux ~]$ stat /dev/uinput
  Файл: /dev/uinput
  Размер: 0             Блоков: 0          Блок В/В: 4096   символьный специальный файл
Устройство: 5h/5d       Инода: 332         Ссылки: 1     Тип устройства: a,df
Доступ: (0600/crw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Доступ:        2020-11-05 00:58:37.713321342 +0700
Модифицирован: 2020-11-05 00:58:37.713321342 +0700
Изменён:       2020-11-05 00:58:37.713321342 +0700
Создан:        -

**Comment by X9VoiD** [comment]
You don't have proper udev rules. Download this [rule](https://github.com/InfinityGhost/OpenTabletDriver-udev/actions/runs/340468496)

Delete `/etc/udev/rules.d/30-opentabletdriver.rules`
Extract zip content as `/etc/udev/rules.d/99-opentabletdriver.rules`

Reboot

**Comment by lmdfmh** [comment]
Pen works and pen binds also works but extra keys on tablet doesn't

**Comment by X9VoiD** [comment]
You may do the following modification to the config to enable aux buttons:

```"ReportParser": "OpenTabletDriver.Vendors.XP_Pen.XP_PenReportParser"```

We're currently holding off on using the aux parsers since there will be a rework that will happen in the near future to support dynamic aux count. (Currently, OTD is hardcoded to support 6 aux buttons)

With that out of the way you may close this issue now.

**Comment by lmdfmh** [comment]
thank you for your help
