### ISSUE TITLE
Cursor jumping to the last place my mouse was

### ISSUE THREAD

**Issue by foodcake** [InfinityGhost/OpenTabletDriver#433]
I've installed the drivers and configured my tablet area, and every second or so my cursor will jump to the last place I used my mouse, I haven't touched anything.
CTL-6100WL
OpenTabletDriver Version 0.4.1
![image](https://user-images.githubusercontent.com/34840618/98482674-1f730080-21c0-11eb-932b-31a6380fccbc.png)
![Untitled](https://user-images.githubusercontent.com/34840618/98482709-6bbe4080-21c0-11eb-978c-6c7ec87e01e1.png)
The 2nd image is a vague example of what I mean, I was circling my pen on the right and my cursor jumps to the top left for some reason, any theories?

**Comment by X9VoiD** [comment]
Open Tablet -> Tablet Debugger, then check what ReportID it says when hovering pen and when pen is out of range

**Comment by foodcake** [comment]
When still and hovering
![image](https://user-images.githubusercontent.com/34840618/98483042-a1fcbf80-21c2-11eb-85f2-3412e7cc82a1.png)
When out of range
![image](https://user-images.githubusercontent.com/34840618/98483049-b0e37200-21c2-11eb-8465-b35d4e11f537.png)

**Comment by X9VoiD** [comment]
So I take it that the ReportID is a range between 16 and 19? Confirm what possible values ReportID can have and under what conditions.

**Comment by foodcake** [comment]
Those are the only values I see, 16 when in range (whether dragging or hovering) and 19 when out of range. I do see the ReportID value flash for a split second, but none of the values on the left change when that happens, only ReportID flashes, and that's when my cursor jumps to the top.

**Comment by X9VoiD** [comment]
Modify `Configurations\Wacom\CTL-6100WL.json` and change ActiveReportID to something like this:

Start: 16
StartInclusive: true
End: 19
EndInclusive: false

Then restart OTD

**Comment by foodcake** [comment]
Thank you so much, that was the issue, have a great day!
