### ISSUE TITLE
Add support for Acepen AP 604

### ISSUE THREAD

**Issue by Ceebox** [InfinityGhost/OpenTabletDriver#451]
This shouldn't be too hard.

Name | Star 06C
-- | --
Manufacturer | Acepen
Product Name | AP604
Width | 6"
Height | 4"
Pressure Levels | 8192
LPI

**Comment by X9VoiD** [comment]
Please use the provided template for tablet configuration requests.

**Comment by X9VoiD** [comment]
While tablet is connected, do `OTD -> Help -> Export Diagnostics`, then upload file here. We cannot add support to a new tablet without the diagnostics.

**Comment by Mrcubix** [comment]
Any news on that?

**Comment by X9VoiD** [comment]
Why is this closed?

**Comment by Ceebox** [comment]
I have attempted to reinstall OpenTabletDriver so I can obtain the required diagnostics. Unfortunately, it appears to corrupt my windows installation every time, and I do not think this is possible.

**Comment by X9VoiD** [comment]
Corrupt your what? OTD doesn't even use admin permissions to "corrupt" Windows.

**Comment by X9VoiD** [comment]
All support for other tablets were added the same way. A diagnostics output is required.

**Comment by Ceebox** [comment]
When I install OTD, my Windows installation corrupts. I get a BSOD and then I am forced to reinstall to the last system restore point.

**Comment by X9VoiD** [comment]
It is not even technically possible for OTD to cause "BSOD", are you sure what you're installing is OpenTabletDriver by InfinityGhost, and not TabletDriver by hawku/devocub?

**Comment by X9VoiD** [comment]
Do be reminded, that OTD runs in user-mode, and *cannot* cause a kernel-level issue like BSoD. If you are having problems with setup, just use the installer provided in [latest release](https://github.com/InfinityGhost/OpenTabletDriver/releases).

**Comment by Ceebox** [comment]
What do you mean? I run the installer, my pc crashes and blue screens. This _is_ and issue with OTD or the installer.

**Comment by X9VoiD** [comment]
[This](https://github.com/InfinityGhost/OpenTabletDriver/releases/download/v0.4.2/OpenTabletDriver.win-x64.zip) is a portable version of OpenTabletDriver. And this is what's being downloaded by the installer. Extract this to a folder where you want to install OTD as long as it's not an admin folder.

Launch `OpenTabletDriver.UX.Wpf.exe`

**Comment by AbstractQbit** [comment]
Don't run ANYTHING as admin, even installer

**Comment by Ceebox** [comment]
It just crashes when I open it.

**Comment by X9VoiD** [comment]
Restart your pc, go to %localappdata% and delete OpenTabletDriver, and then launch the portable again.

**Comment by Ceebox** [comment]
Unfortunately, this still does not work.
I would like to help people using this driver with this tablet, however I am unable to get this to work.

**Comment by X9VoiD** [comment]
Open Event Viewer -> Windows Logs -> Application.

Click on the latest log where it says `.NET Runtime`

Screenshot the contents of the log

**Comment by Ceebox** [comment]
`Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: OpenTabletDriver.Installer.exe
P2: 0.4.1.0
P3: 5f1757ad
P4: RTSSHooks64.dll
P5: 0.0.0.0
P6: 5c83708c
P7: c0000005
P8: 0000000000019fe9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER310B.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_OpenTabletDriver_909ed87733f8928dbf68de569dbd48183b7f9653_306c3ef2_84aa3cb9-5c60-43aa-8891-e0d58227206b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2e19cd29-cdaa-4530-855c-5d375f13e073
Report Status: 268435456
Hashed bucket: 0c7744a2207e9e0271b4b6f1a330472d
Cab Guid: 0`

`Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: OpenTabletDriver.Installer.exe
P2: 0.4.1.0
P3: 5f1757ad
P4: RTSSHooks64.dll
P5: 0.0.0.0
P6: 5c83708c
P7: c0000005
P8: 0000000000019fe9
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_OpenTabletDriver_909ed87733f8928dbf68de569dbd48183b7f9653_306c3ef2_84aa3cb9-5c60-43aa-8891-e0d58227206b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2e19cd29-cdaa-4530-855c-5d375f13e073
Report Status: 4
Hashed bucket: 
Cab Guid: 0`

There are two, so I posted both but I think they are the same.

**Comment by AbstractQbit** [comment]
You are still launching the installer, use portable that X9VoiD sent you.

**Comment by Ceebox** [comment]
Sorry, I have edited it. I copied the wrong one.

**Comment by X9VoiD** [comment]
This is not the log that we need. The log should have a header looking something like:
```
Application: OpenTabletDriver.UX.Wpf.exe
CoreCLR Version: 5.0.20.51904
.NET Version: 5.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: Error something something
```

**Comment by Ceebox** [comment]
Well, that is unfortunate, because all the logs I can find do not look like that.

![unfortunate](https://user-images.githubusercontent.com/49747230/102012648-85185680-3d43-11eb-992d-db9dc656ff53.gif)

**Comment by X9VoiD** [comment]
From that log it's now clear what the problem is. RivaTuner is most likely overriding a default behaviour that OTD expects (through that RTSSHooks64.dll).

An OTD crash looks like this 
![image](https://user-images.githubusercontent.com/10338031/102012715-02b18600-3d87-11eb-96a1-6e974854c202.png)

And the logs you've sent is an error external to OTD, since it did not came from CoreCLR (.NET Runtime)

Unfortunately, you *have* to uninstall RivaTuner and just use the official gpu drivers to tweak your stuff.

**Comment by Ceebox** [comment]
Ah, that is unfortunate. Looks like I'm just going to have to go with the default settings and just try and adjust stuff in photoshop.
