### ISSUE TITLE
s620 problems (lubuntu)

### ISSUE THREAD

**Issue by wagwanfam** [InfinityGhost/OpenTabletDriver#452]
## Description

tablet wont detect, also cant figure out how to save custom configurations so i cant try to use that to fix
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | lubuntu
| Software Version | v0.4.1 (because 0.4.2 wont install, cant get dot net 5 working)
| Tablet           | s620

**Comment by wagwanfam** [comment]
"[Normal:Detect]	Searching for tablet 'Gaomon S620'
[Error:Detect]	Failed to get device input report length. Ensure the 'hid-uclogic' module is disabled."
^ message only appears after looking for s620 and some random huion tablets
so i did "sudo modprobe -r hid-uclogic"
and now i get  an error that says "[Error:HidSharp.Exceptions.DeviceIOException]	Unable to open HID class device (OK)."
no random googling helped me here :C

**Comment by Mrcubix** [comment]
device string and or init string is wrong in your config

**Comment by Mrcubix** [comment]
```
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update && \
sudo apt-get install -y dotnet-runtime-5.0
```
yoinked from void

**Comment by wagwanfam** [comment]
right that fixed install
opened OTD 0.4.2 and still no detect
console reads 
"
[Detect:Info]	Searching for tablet 'Gaomon S620'
[DeviceIOException:Error]	Unable to open HID class device (OK).
"
iv wrote my own script now for my tablet to play osu!  but i wouldn't mind still helping resolve this issue in case others experience this

**Comment by X9VoiD** [comment]
`sudo udevadm control --reload-rules && sudo udevadm trigger`

**Comment by wagwanfam** [comment]
[ArgumentOutOfRangeException:Error]	Value range is [0, 15]. (Parameter 'value')
new error,(well first error i had b4 i was messing around)

**Comment by X9VoiD** [comment]
Reboot

**Comment by wagwanfam** [comment]
been out for exam came back, reeboted, same error

**Comment by X9VoiD** [comment]
Blacklist `hid_uclogic` module

**Comment by X9VoiD** [comment]
```
sudo rmmod hid_uclogic
sudo udevadm control --reload-rules && sudo udevadm trigger
systemctl --user restart opentabletdriver.service
```
