### ISSUE TITLE
Cursor jumps to corner of the area

### ISSUE THREAD

**Issue by b4mbus88** [InfinityGhost/OpenTabletDriver#456]
Hi,
iam using the Wacom PTH-660 and I cant use my mouse while the tablet is running. Wacom Drivers are uninstalled. 
Technicly the mouse is working but every ~2 seconds the cursor is jumping to the corner of the tablet area. 
If iam using the pen to move the cursor everything works fine.

Edit: Iam running on windows installer v0.4.1 right release now.

There is some Warning and error too. Maybe it will help to solve the problem.

[Detect:Info]	Searching for tablet 'Wacom PTH-660 Bluetooth'
[Detect:Info]	Searching for tablet 'Wacom PTH-660'
[Detect:Info]	Found tablet 'Wacom PTH-660'
[Detect:Warning]	More than 1 matching auxiliary device has been found.
[Device:Error]	Failed to open stream.
[DeviceIOException:Error]	Unable to open HID class device (\\?\hid#vid_056a&pid_0357&mi_00&col01#7&25ebc169&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}).
[NullReferenceException:Error]	Object reference not set to an instance of an object.

**Comment by X9VoiD** [comment]
Download [PTH-660.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5564117/PTH-660.zip) then extract and replace `Configurations/Wacom/PTH-660.json`.

After replacing, restart OTD then check again.

**Comment by b4mbus88** [comment]
Still the same issue. As soon as i lay down my pen to use the mouse, the cursor is jumping to the corner every 2sec

**Comment by X9VoiD** [comment]
Open Tablet Debugger then check what ReportID it says during hover, and when pen is not in range.

**Comment by b4mbus88** [comment]
During hover
![hover](https://user-images.githubusercontent.com/53981205/99617334-7201b780-2a1f-11eb-8bf3-3c54940ff4ed.png)
No hover
![no_hover](https://user-images.githubusercontent.com/53981205/99617339-77f79880-2a1f-11eb-9912-f96c60251b39.png)

**Comment by X9VoiD** [comment]
Is ReportID changing during hover based on distance?

**Comment by b4mbus88** [comment]
Yes, ReportID is changeing to 19 as soon as i leave the tablet. I guess its around 2cm away from the real tablet area. dosent matter in which direction.

**Comment by b4mbus88** [comment]
And the cursor is instantly jumping to the corner as soon ReportID is going to 19

**Comment by X9VoiD** [comment]
Okay, I got what I need now, but just for verification, open Tablet Debugger again, then hover pen to bottom-right most part of the tablet and try to get the highest possible value for Position. Press down the pen to try to get the highest Pressure possible, then report those values here.

Also do Help -> Export Diagnostics then upload the file here. (to possibly fix the warnings)

**Comment by b4mbus88** [comment]
Export Diagnostics
[diag.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5564224/diag.txt)
Tablet Debugger
![bottomRight](https://user-images.githubusercontent.com/53981205/99618896-957a3180-2a22-11eb-9cc5-f82a97a7267d.png)

Dont know if it is important, but i rotated the tablet area 180°

**Comment by X9VoiD** [comment]
Get the highest value for Position

**Comment by b4mbus88** [comment]
44800, 29600
Pressure 8191

Post above is edited with the picture

**Comment by X9VoiD** [comment]
This [PTH-660.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5564261/PTH-660.zip) should fix the cursor teleport issue and the warning.

**Comment by b4mbus88** [comment]
Sadly it still teleporting :( 
I remembered I used hawku/TabletDriver before. I uninstalled Wacom drivers but do i have to remove vmulti_drivers from hawku too?

**Comment by X9VoiD** [comment]
Are you sure you replaced the existing configuration and restarted OTD?

**Comment by b4mbus88** [comment]
Yes. I tried it again now, but it still dosent work.

**Comment by b4mbus88** [comment]
Ohh.. If iam opening via Daemon it works. If iam using OpenTabletDriver.Installer.exe to start it is not working. Let me check if there is another folder

**Comment by X9VoiD** [comment]
[PTH-660.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5564275/PTH-660.zip)

I changed the name just to make sure. Check on logs if it's detected as "PTH-660 Test"

**Comment by b4mbus88** [comment]
Yeah. Iam stupid. Both of your last files work. There is just one installation folder in appdata and one in my downloads.
Thank you very much for helping fixing the problem!

**Comment by X9VoiD** [comment]
You may close the issue now and no problemo :bread:
