### ISSUE TITLE
Does opentabletdriver support pen pressure?

### ISSUE THREAD

**Issue by Turk3ysandwich** [InfinityGhost/OpenTabletDriver#468]
# Support Request
 I use the tablet for osu mostly but some drawing and autodesk sketchbook supports pen pressure. Am I doing something wrong?

**Comment by solonovamax** [comment]
It supports pen pressure in some applications. I know that it works in krita, but doesn't seem to work for me in gimp.
(You need to switch it to "artist mode" to enable it. This is for linux, idk for windows.)

**Comment by Mrcubix** [comment]
there is a plugin just for that, https://github.com/X9VoiD/VoiDPlugins/releases/download/v0.2.1/WindowsInk.zip put that in %localappdata%/opentabletdriver/Plugins

**Comment by Mrcubix** [comment]
also you need to install this https://github.com/X9VoiD/vmulti-bin/releases/tag/v1.0

**Comment by Mrcubix** [comment]
when done, switch to artist mode in otd

**Comment by X9VoiD** [comment]
This issue should be closed as we already have pressure support for Windows in the form of a plugin

**Comment by InfinityGhost** [comment]
> This issue should be closed as we already have pressure support for Windows in the form of a plugin

Agreed.

**Comment by Turk3ysandwich** [comment]
> when done, switch to artist mode in otd

It's me spaghetti lol
