### ISSUE TITLE
OpenTabletDriver.UX.Wpf.exe not starting

### ISSUE THREAD

**Issue by jupiteria47** [InfinityGhost/OpenTabletDriver#485]
## Description

When i open OpenTabletDriver.UX.Wpf.exe, nothing happens
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 7
| Software Version | 0.4.2
| Tablet           | Huion H430P

**Comment by InfinityGhost** [comment]
Software version is asking for OpenTabletDriver version, probably should clarify that in the template lol

Anyway, are you familiar with how to use event viewer?

**Comment by jupiteria47** [comment]
idk how to use that

**Comment by jupiteria47** [comment]
> Software version is asking for OpenTabletDriver version, probably should clarify that in the template lol
> 
> Anyway, are you familiar with how to use event viewer?

idk what is that and how to use it

**Comment by Mrcubix** [comment]
make sure you installed .net 5 Runtime x64

**Comment by jupiteria47** [comment]
> make sure you installed .net 5 Runtime x64
> https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.0-windows-x64-installer

oh yeah i4got i only have .net framework 4.7

**Comment by jupiteria47** [comment]
Update: i have installed .net 5 runtime, nothing still happens when i open the installer

**Comment by X9VoiD** [comment]
You may just download `OpenTabletDriver.win-x64.zip` directly from Assets of [latest releases](https://github.com/InfinityGhost/OpenTabletDriver/releases/latest).

**Comment by jupiteria47** [comment]
> You may just download `OpenTabletDriver.win-x64.zip` directly from Assets of [latest releases](https://github.com/InfinityGhost/OpenTabletDriver/releases/latest).

this is what i downloaded yesterday and OpenTabletDriver.UX.Wpf.exe doesn't open

**Comment by jupiteria47** [comment]
nvm imma just close this issue and download the installer instead of the portable
