### ISSUE TITLE
Add support for Xp-Pen Star G540

### ISSUE THREAD

**Issue by Spoiler135** [InfinityGhost/OpenTabletDriver#516]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | Xp-Pen |
| Product Name    | Star G540 |
| Width           | 140mm |
| Height          | 120mm |
| Pressure Levels | 2048 |
| LPI             | 5080 |

## Diagnostic Information

[w.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5646905/w.txt)

**Comment by X9VoiD** [comment]
Close OTD, extract [G540.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5646970/G540.zip) to `Configuration\XP-Pen\G540.json`

**Comment by Spoiler135** [comment]
I'm sorry but I can't go to the right side of monitor
![2020-12-05-22-43-15_Trim](https://user-images.githubusercontent.com/50593660/101258485-f60cac80-374c-11eb-8aa4-f098455848d6.gif)

**Comment by X9VoiD** [comment]
OTD -> Tablet -> Tablet Debugger

Hover around the edges and try to get the highest possible value for Position

**Comment by Spoiler135** [comment]
I got Position:[45707, 29208]

**Comment by X9VoiD** [comment]
Make sure that *that* is the highest possible value since even just a single digit error will cause issues

**Comment by Spoiler135** [comment]
Sorry, it turned out to be Position:[45720, 29210]

**Comment by X9VoiD** [comment]
[G540.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5647709/G540.zip)

**Comment by Spoiler135** [comment]
It works fine. Thank you so much!

**Comment by InfinityGhost** [comment]
Reopening until the configuration is merged to master.
