### ISSUE TITLE
ArgumentOutOfRangeException when detecting tablets

### ISSUE THREAD

**Issue by zsinx6** [InfinityGhost/OpenTabletDriver#517]
## Description
I'm having issues with the Gaomon S620:
`[ArgumentOutOfRangeException:Error]	Value range is [0, 15]. (Parameter 'value')`
Resulting in the tablet not being detected

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Arch Linux 
| Software Version | Master build from AUR
| Tablet           | Gaomon S620

**Comment by X9VoiD** [comment]
Check wiki on how to blacklist `hid_uclogic` and reload udev

**Comment by zsinx6** [comment]
Solved, thank you!

**Comment by gonX** [comment]
I've seen a few people with this issue now, and the fix has always been to check if any kernel modules that can grab the device are still loaded. Perhaps the [Wiki entry](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#argumentoutofrangeexception-value-0-15) should be changed so it doesn't just ask people to install the udev rules?
> Build and install the udev rules with the script above.

I'd be willing to submit a PR if there is interest.

**Comment by InfinityGhost** [comment]
> I've seen a few people with this issue now, and the fix has always been to check if any kernel modules that can grab the device are still loaded. Perhaps the [Wiki entry](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#argumentoutofrangeexception-value-0-15) should be changed so it doesn't just ask people to install the udev rules?

If there's a good way to check what module is controlling a device this could be automated in a script quite easily.
