### ISSUE TITLE
Dependency issue on latest .deb installer

### ISSUE THREAD

**Issue by skatunerd** [InfinityGhost/OpenTabletDriver#523]
## Description

Ran the .deb installer and it complains about not being able to satisfy dependency `dotnet-runtime-5.0`. Where do I download this dependency?
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Linux Mint 20 Cinnamon Kernel 5.4.0-26-generic
| Software Version | Latest .deb package
| Tablet           | XP-PEN G960

**Comment by InfinityGhost** [comment]
You did not install `packages-microsoft-prod.deb`.

https://github.com/InfinityGhost/OpenTabletDriver/wiki/Installation-Guide#debianubuntu-installation
