### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by RealKimboS** [InfinityGhost/OpenTabletDriver#529]
# Support Request
 genius i405x tablet drivers make the cursor in osu stuck in the corner 
 when i try to play with genius drivers it make my cursor get stuck in the top left corner of the screen no matter what area i use its a big problem for me because i its feel a little bit bad playing by changing the sensitivity 

## What I've already tried
https://osu.ppy.sh/community/forums/topics/252546

**Comment by InfinityGhost** [comment]
oops i linked the wrong template, make a new issue with [this one](https://github.com/InfinityGhost/OpenTabletDriver/issues/new?assignees=&labels=configuration&template=tablet_configuration.md&title=Add+support+for+)
