### ISSUE TITLE
Left handed mode

### ISSUE THREAD

**Issue by Recilia** [InfinityGhost/OpenTabletDriver#532]
This Driver Great!
but im having a hard time fully transferring to this driver due to no Left Handed mode.
Why need this you ask?
Well im a right handed but because of complex setup i have to put my CTL-472 on left handed so that the cable isnt all messed up
I know this feature will be added to the future but just bringing this up now so that i can actually try the new Driver with no problems.

Thank you. <3

**Comment by AbstractQbit** [comment]
Already implemented in #528 , use action build from that branch to test it out (https://github.com/InfinityGhost/OpenTabletDriver/actions/runs/409491648), or set 180° rotation manually for now

**Comment by Recilia** [comment]
thank you so much!
