### ISSUE TITLE
Support Request: Gaomon S620 Linux "ArgumentOutOfRange"

### ISSUE THREAD

**Issue by XSonicRU** [InfinityGhost/OpenTabletDriver#535]
Hello there.
Idk bug or not, so issuing as support request
My Gaomon S620 isn't being detected.
![image](https://user-images.githubusercontent.com/22415344/101715804-cf9d9700-3ae7-11eb-930c-b70d416092d3.png)
Have no idea how to fix - tried to generate new config from a connected s620 (gets detected as HUION tablet btw), and playing around with values. Still the same error. It also is present on a number of other "detect" attempts, with different tablets.
Thanks in advance.  
btw im using arch

**Comment by Mrcubix** [comment]
first, following the template would had been nice, 
second, 
```
sudo rmmod wacom; sudo rmmod hid_uclogic
sudo udevadm control --reload-rules && sudo udevadm trigger
```
then restart OTD

**Comment by XSonicRU** [comment]
Sorry for not following the template, thought there was too much unneeded bloat there.
But, your advice has changed something apparently.
first two commands gave "module is not loaded"
After executing latter two I've restarted otd and nothing has changed.
I've tried to reinstall otd, just in case, and now I have a different error. Interesting.
![image](https://user-images.githubusercontent.com/22415344/101726399-3037ce80-3afe-11eb-8e91-f467a0059e90.png)

**Comment by XSonicRU** [comment]
So, I've done a little bit of tinkering there, have found some interesting details, although no solution.
First of all, the exception gets called by the lack of these values on one of HID devices
![image](https://user-images.githubusercontent.com/22415344/102215854-062f4380-3f26-11eb-97ea-9a0ad05ddd68.png)
But the thing is, It actually has 2 instances of my tablet
![image](https://user-images.githubusercontent.com/22415344/102215963-2ced7a00-3f26-11eb-8df1-17a317ab8b91.png)
And they are not identical. Bottom one has these values, and upper one doesn't. So, I thought that the issue might be that it just crashes on the upper one and doesn't even get to check the lower one. So, I've removed checks for these values in driver.
![image](https://user-images.githubusercontent.com/22415344/102218549-db46ee80-3f29-11eb-936e-09f8cc0be816.png)
Hooray, no error, it detects successfully. But, driver doesn't seem to be working, no input. And neither it has any errors in its log. And it feels like I'm stuck here as I have no idea on how to debug the whole tablet-driver connectivity. I'm going to try tinkering with it a little more though, maybe will get lucky or anything.
Of course, any help would be welcome.

**Comment by LavaDesu** [comment]
Are you using the AUR package or are you compiling and running it yourself?
This is most likely caused by misconfigured udev rules

**Comment by XSonicRU** [comment]
Im using AUR.
But also compiling and running myself when debugging, right?
What's that even supposed to mean, lol

Udev rules? Never touched them myself though. Only did the stuff that the guy above advised, but it only reloads or something anyway.

**Comment by XSonicRU** [comment]
Wait.
Just redone commands from above and 
IT WORKS.
Man I swear I was doing that before several times, for what godsaken reason did it only work now...
Why were they misconfigured it the first place though...
Anyway, thank you all.
