### ISSUE TITLE
Cursor wont work in Windows applications 

### ISSUE THREAD

**Issue by MkGuh** [InfinityGhost/OpenTabletDriver#539]
## Description
Cursor wont work in Windows applications like Task Manager, cmd, etc

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Windows 10 64 bit |
| Latest |
| CTL-480         |

**Comment by X9VoiD** [comment]
This is an expected behaviour and won't fix for security reasons. OpenTabletDriver runs in user-mode by default and will not be able to send input to elevated processes.

**Comment by AbstractQbit** [comment]
Duplicate of #347 and #469.
