### ISSUE TITLE
Add support for Huion G10T

### ISSUE THREAD

**Issue by cantnot** [InfinityGhost/OpenTabletDriver#541]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | HUION
| Product Name    | Huion G10T
| Width           | 374mm
| Height          | 177mm
| Pressure Levels | 8192
| LPI             | 5080

## Diagnostic Information

[w.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5676147/w.txt)

**Comment by Mrcubix** [comment]
[Huion G10T.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5676157/Huion.G10T.zip)
put that config in configuration/Huion

**Comment by cantnot** [comment]
HUION_T161_170531

**Comment by Mrcubix** [comment]
[Huion G10T.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5676304/Huion.G10T.zip)

**Comment by cantnot** [comment]
the cursor sticks to the top left corner of my monitor, it identifies my tablet as Huion GT-133 in the console, it does seem to be catching coordinates in the debugger, report id is 64 it doesnt change, it registers clicks from both buttons, but it doesnt work my cursor is always stuck in the top right corner

**Comment by cantnot** [comment]
report ID seems to be always at 64, debug is registering clicks, pressure and position, when positioning my pen on the top it seems to get to the top on my screen before i get to the top with my tablet and i cant reach the bottom of my screen or the right side

**Comment by Mrcubix** [comment]
you need to be slow else it just won't work,

**Comment by Mrcubix** [comment]
any news?
