### ISSUE TITLE
Add Tablet Report Rate Change

### ISSUE THREAD

**Issue by ericwong0711** [InfinityGhost/OpenTabletDriver#545]
add like hawkuTabletdriver Smoothing Filther can change latency and rate
let me overclock my CTH 680 to 10ms 1000hz rate
because CTH680 default only have 136hz rate
on my 240hz monitor tablet input rate only have 136hz rate is look like shit
input rate 1000hz is more smoothly
![IMG 2020-12-12 07 59 21](https://user-images.githubusercontent.com/52947234/101970677-c7b83100-3c66-11eb-9c04-83ff07f959a5.png)

**Comment by InfinityGhost** [comment]
This is covered by interpolation in v0.5.0-dev already. Some plugins already make use of it, i.e. https://github.com/X9VoiD/VoiDPlugins.

Just a heads up, its not truly an "overclock". It estimates position between two data points, where an overclock would make the device report more frequently.
