### ISSUE TITLE
Cursor jumping to the side when moving a pen

### ISSUE THREAD

**Issue by lisophoria** [InfinityGhost/OpenTabletDriver#546]
Just installed this driver, configured an area and tried to play osu. The cursor is jumping somewhere like shown in picture below

![screenshot001](https://user-images.githubusercontent.com/39840328/101984159-aff5a280-3c90-11eb-9956-a701c8b378d3.jpg)

This issue is systemwide.

Im runnin on Linux neon KDE that was built on ubuntu. My tablet is CTL-672. Any ideas?

**Comment by InfinityGhost** [comment]
Could be a configuration issue, will have to cross check the 472 and 672 configs

**Comment by X9VoiD** [comment]
This is a double cursor bug. Check wiki on how to fix that.

**Comment by Evernow** [comment]
If anyone else encounters this, in the wiki it is referenced as "ghost cursor" https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#i-have-a-ghost-cursor-constantly-alternating-cursor-position
