### ISSUE TITLE
Support for H1060P?

### ISSUE THREAD

**Issue by czarchasm00** [InfinityGhost/OpenTabletDriver#564]
# Support Request
I see that the Huion New 1060 Plus is listed as being supported in your Supported Tablets list. However, the Huion H1060P is not. (AFAIK) The notable difference between the two is that the H1060P does not have a battery in its pen that you have to charge or replace, and it also has 8192 pressure levels. The H1060P is commonly known as the "upgraded version" to the New 1060 Plus (AFAIK), so I am unaware if the drivers are different.
My main question is this: Are the H1060P and New 1060 Plus using the same drivers and this is an issue on my end, or will the H1060P require its own driver support.

Notably, the TabletDriver project from hawku is able to detect that it is a Huion tablet, and my pen's position (using debugger), but it does not know which one it is or actually put inputs through, so I'm thinking it does indeed use different drivers.

## Diagnostic Information
Help -> Export Diagnostics: https://pastebin.com/kBZ8UsLt
Windows 10 Pro: Version 10.0.19042 Build 19042
Exact Amazon page that I ordered it from: https://www.amazon.com/dp/B07D9BH3NM (just for model information)
Model (obtained from back of tablet) H1060P

**Comment by X9VoiD** [comment]
OTD -> Tablet -> Device string reader
```
Vendor ID: 9580
Product ID: 109
String Index: 201
```
Hit Send Request, and then paste result here

**Comment by czarchasm00** [comment]
HUION_T167_190325

**Comment by X9VoiD** [comment]
Make sure you don't have any tablet drivers anymore. If you do, please uninstall them first including WinUSB.

Download latest [dev build](https://github.com/InfinityGhost/OpenTabletDriver/actions/runs/426981263). Extract it to any folder of choice as long as it's not an admin-requiring folder.

Extract [H1060P.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5706866/H1060P.zip) as `Configurations\Huion\H1060P.json` and then launch `OpenTabletDriver.UX.Wpf.exe`

**Comment by czarchasm00** [comment]
I have already removed the "Graphics Tablet Device" from the Device Manager, as well as ticking the box to uninstalling it. I've uninstalled the Huion official drivers through uninstalling the official driver program. I'm not entirely sure what WinUSB is; is that another driver? I don't seem to have anything named "WinUSB" in my Device Manager.

Regardless of that, your instructions worked perfectly. After installing the new .NET 5.0 Runtime, my tablet is recognized properly with the new dev build and I am able to use it without any issues (so far). Thank you so much.

**Comment by X9VoiD** [comment]
For verification processes, go to Tablet -> Tablet Debugger, hover your pen around the edges of the tablet and try to get the highest possible value for Position

**Comment by czarchasm00** [comment]
I got both of those exact values. Apologies for closing this issue early.
![ku0epqfSAb](https://user-images.githubusercontent.com/76140847/102442819-e7df4b80-3fea-11eb-9076-f4597abf646c.png)
Let me know if there is any additional info you would like me to provide.

**Comment by X9VoiD** [comment]
No problems, we're good, H1060P support will come on next official release :bread:

For now you may use the dev build that you currently have, and if you want to update your dev build, go [here](https://github.com/InfinityGhost/OpenTabletDriver/actions), find latest `master`, and then place the config I sent you.
