### ISSUE TITLE
Support Request: Tablet not detected [Star G640] [Arch Linux]

### ISSUE THREAD

**Issue by straightcurve** [InfinityGhost/OpenTabletDriver#566]
# Support Request
I followed the Arch Linux instructions, no problems encountered during the installation, however the tablet is not recognized.

## What I've already tried
I was using the wacom driver for the tablet before finding out about OTD, I tried removing the `/etc/X11/xorg.conf.d/52-tablet.conf` file I was using for it.
These are the contents of the `52-tablet.conf`, maybe you could find it useful:
> Section "InputClass"
        Identifier "Tablet on WizardPen"
        #MatchIsTablet "on"
        #MatchProduct "XP-PEN STAR G640 Pen"
        MatchDevicePath "/dev/input/event*"
        MatchUSBID "28bd:0094"
        Driver "wacom"
        # Apply custom Options below.
        #Option "TopX" "0"
        #Option "TopY" "0"
        #Option "BottomX" "21845"
        #Option "BottomY" "18255"
EndSection

I tried restarting the machine.
Executing `systemctl status --user opentabletdriver.service` gives me this:
![image](https://user-images.githubusercontent.com/31109115/102483556-962bd500-406d-11eb-8408-afb220314250.png)
I don't know where to find the logs haha
I have the `libevdev-git` package installed btw, I couldn't find anything regarding `libevdev2` as specified in the dependency list on the README.

## Diagnostic Information
I tried to export diagnostics, but it's coming out as a 0 bytes file.
`Linux 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux`

**Comment by InfinityGhost** [comment]
Run `journalctl --user-unit opentabletdriver.service` and try to get that full exception in text.

**Comment by straightcurve** [comment]
![image](https://user-images.githubusercontent.com/31109115/102557601-42a0a200-40d4-11eb-9d0b-34f6c32f5c89.png)

**Comment by X9VoiD** [comment]
Replug tablet or retrigger udev through `sudo udevadm trigger` and then restart OTD daemon and UX

**Comment by straightcurve** [comment]
nothing changed, also this is what the console says:
![image](https://user-images.githubusercontent.com/31109115/102562514-e479bc00-40df-11eb-844a-6bdaa7602d58.png)

**Comment by X9VoiD** [comment]
From: https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ
```
echo "blacklist hid_uclogic" | sudo tee -a /etc/modprobe.d/blacklist.conf
sudo rmmod hid_uclogic
```

**Comment by straightcurve** [comment]
I have not seen the FAQ page, thank you, it works now.
