### ISSUE TITLE
Area automatically changing upon restart of driver.

### ISSUE THREAD

**Issue by Myekel** [InfinityGhost/OpenTabletDriver#572]
## Description

Setting my area to
Width: 67
Height: 42
Xpos: 114.54
Ypos: 70.83
Rotation: 180
I get this weird thing where it automatically changes to itself to (upon restarting)
Width: 67
Height: 42
Xpos/offset: 118.5
Ypos/offset: 74
Rotation: 180
Could this get looked at? is withholding me from actually using the drivers since its really annoying to continuesly fix my area.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Win 10 2004
| Software Version | 0.4.2
| Tablet           | CTH-480

**Comment by Mrcubix** [comment]
make your area, save it, upload your settings.json ( found in %localappdata%/opentabletdriver/ )
restart OTD, save, and upload settings.json for the second time

**Comment by Myekel** [comment]
Okay so you want me to upload them here?

**Comment by Myekel** [comment]
[settings1.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5719575/settings1.zip)
[settings2.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5719576/settings2.zip)

**Comment by Myekel** [comment]
Oh btw, When changing area position values to the values above they get changed again when putting rotation to 180.

**Comment by Mrcubix** [comment]
this seem to be in reality, a UX bug, the values are the same, as well ass probably for the daemon too

**Comment by Mrcubix** [comment]
you're using 180 rotation cause you're left handed?

**Comment by Mrcubix** [comment]
https://cdn.discordapp.com/attachments/615611007951306863/786267880207417374/Lefty_Flip_Mode.dll

put this in your plugin folder

**Comment by Myekel** [comment]
I use 180 cuz there is a scratch on the topleft of my tablet so i flipped my tablet upside down to still play with topleft.

**Comment by Myekel** [comment]
When using the plugin it still gets set to x: 118.5 y: 74

**Comment by Myekel** [comment]
nvm
I now have to put my area to the topleft of my tablet of course.

**Comment by AbstractQbit** [comment]
@Myekel could you try reproducing your issue on the latest dev build? Because I don't encounter such behaviour there, it saves exactly what's in the field.
https://github.com/InfinityGhost/OpenTabletDriver/actions/runs/431969720

**Comment by Myekel** [comment]
I will try it

**Comment by Myekel** [comment]
Allright! Seems to be working flawlessly! thank you for help!
