### ISSUE TITLE
XP-Pen G640 cannot be opened

### ISSUE THREAD

**Issue by nerd** [InfinityGhost/OpenTabletDriver#58]
## Description
Trying to use an XP-Pen G640 tablet results in a DeviceIOException stating that the device cannot be opened.

![Screenshot](https://user-images.githubusercontent.com/13791487/70857684-3ed6b000-1ec1-11ea-80cc-83a120196200.png)

## System Information:
Option            | Value
------------------|------------------
Operating System  |  Windows 10
Software Version  | 0.1.0-1301bbb
Tablet            |  XP-Pen G640

**Comment by InfinityGhost** [comment]
Installing the XP-Pen drivers seems to unlock the HID stream, allowing it to be opened. Hopefully I can make this not a requirement, but it may come down it that its required.

**Comment by InfinityGhost** [comment]
Issue is noted in the [wiki](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Windows-FAQ#my-xp-pen-tablet-fails-to-open-deviceioexception-unable-to-open-hid-class-device) until a further fix is found.

**Comment by selplacei** [comment]
Experiencing the same bug on Arch Linux, kernel version 5.4.7-arch1-1

**Comment by MoeLava** [comment]
For Linux, you need to have udev rules to gain access to the device stream. See the [FAQs](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#the-driver-fails-to-open-the-tablet-deviceioexception)

**Comment by InfinityGhost** [comment]
General agreement that as of right now, the consistent fixes are located in the wiki. Closing but keeping this in mind for future improvements.
