### ISSUE TITLE
Support Request: veikk s640

### ISSUE THREAD

**Issue by cstanyar2007** [InfinityGhost/OpenTabletDriver#584]
hi i got my first tablet the veikk s640 but im on linux so i downloaded the tabletdriver it  hassent been tested i dident see it on any of the list of untested and supoerted and that so

**Comment by X9VoiD** [comment]
Veikk S640 is already supported (https://github.com/InfinityGhost/OpenTabletDriver/projects/4#card-31065233).

If you encounter any problems refer to the [wiki](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ).

You may close this issue now.
