### ISSUE TITLE
Abnormal CPU usage when tablet is (dis)connected after startup

### ISSUE THREAD

**Issue by MoeLava** [InfinityGhost/OpenTabletDriver#61]
## Description

After opening OpenTabletDriver without a tablet connected, manually connecting it afterwards will cause the CPU usage to jump to 100% and persist until closed.
Opening OpenTabletDriver with a tablet connected and disconnecting the tablet afterwards will also cause the same issue.
![image](https://user-images.githubusercontent.com/56823419/70973384-2c828f00-20d8-11ea-9c20-6af8ec8548df.png)

## System Information:

Option            | Value
------------------|------------------
Operating System  | Arch Linux
Software Version  | 0.1.0-4eff49e4
Tablet            | Gaomon S620

**Comment by InfinityGhost** [comment]
This is likely an issue embedded in the HidSharp library, and I'm going to look for a proper fix if I can.

**Comment by maxerium** [comment]
Did some pinpointing on this issue, and found out that it also happens on other HID devices (keyboards, mice, etc.) - CPU usage still ramps up. On other USB devices nothing happens, usage stays normal.

## System Info:
Setting | Value
----- | -----
Distro | Manjaro (5.4.12-xanmod7 kernel)
Driver Version | 0.1.0-8f72f61
Tablet | Wacom CTL-470

**Comment by InfinityGhost** [comment]
Reproduced it and followed the trace here, it seems to end up on an endless retry loop when a device disconnects.
https://streamable.com/ftgji

**Comment by maxerium** [comment]
Commit a8b85decb62759dc4c840d21107a324b4fc12d95 fixes this - did some testing. Excited for 0.1.1.
