### ISSUE TITLE
problem with filters

### ISSUE THREAD

**Issue by reodeza** [InfinityGhost/OpenTabletDriver#617]
## Description

Hawku and Devocub filters doesnt showing in filters menu after installation them and restarting driver
![explorer_2021-01-02_17-02-57](https://user-images.githubusercontent.com/38606782/103455188-7b1fbd00-4d1d-11eb-91e7-5822fc4c694d.png)

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Win 10 1909
| Software Version | v0.4.2
| Tablet           | CTH-680

**Comment by X9VoiD** [comment]
Make sure you're using the correct filter version, This [TabletDriverFilters](https://github.com/OpenTabletDriver/TabletDriverFilters/releases/tag/v0.1.0) release is compatible only with OTD 0.5.x. Check out #faq channel of Discord server for the OTD 0.4.2 compatible version.

Do note tho that the 0.4.2 compatible version have limitations, such as inability to fake report rate (so timer interval have to be set to tablet report rate), and slightly incorrect devocub implementation.

Use the 0.5.0 prerelease instead if you need any of the features mentioned above.

**Comment by reodeza** [comment]
oh, ok thx, sorry for the opened issue

**Comment by X9VoiD** [comment]
You may close this issue if you don't have any problems anymore.

**Comment by InfinityGhost** [comment]
Issue appears resolved, closing.
