### ISSUE TITLE
Support Request: Cant start the tablet driver 

### ISSUE THREAD

**Issue by rumeie** [InfinityGhost/OpenTabletDriver#621]
# Support Request

![image](https://user-images.githubusercontent.com/18748818/103478758-d5934900-4e03-11eb-9df2-601c8e5b686a.png)
after I click Start it show this 
![image](https://user-images.githubusercontent.com/18748818/103478782-f6f43500-4e03-11eb-918f-084f7ae978c0.png)

and return back to 
![image](https://user-images.githubusercontent.com/18748818/103478758-d5934900-4e03-11eb-9df2-601c8e5b686a.png)

https://user-images.githubusercontent.com/18748818/103478838-5f431680-4e04-11eb-8279-5e70c3881cac.mp4

## What I've already tried

Uninstall and reinstall the driver
## Diagnostic Information

after clicking Export Diagnostics generate this file

[daemon.log](https://github.com/InfinityGhost/OpenTabletDriver/files/5761604/daemon.log)

https://user-images.githubusercontent.com/18748818/103479002-599a0080-4e05-11eb-9d7c-e3a54d739767.mp4

**Comment by X9VoiD** [comment]
Delete `%localappdata%/OpenTabletDriver/settings.json`

**Comment by rumeie** [comment]
ok thx resolved
