### ISSUE TITLE
OpenTabletDriver Two Monitors

### ISSUE THREAD

**Issue by Liedaazn** [InfinityGhost/OpenTabletDriver#629]
I recently installed a new monitor and every time I use my tablet, the cursor will start teleporting between the spot my cursors at and a different place. It'll keep doing this unless I have hover just in the tablet range.

| Windows 10 |
| Tablet XP-PEN G430S_ |

**Comment by X9VoiD** [comment]
Make sure you've uninstalled all other tablet drivers before using OTD.

**Comment by Liedaazn** [comment]
> Make sure you've uninstalled all other tablet drivers before using OTD.

I have uninstalled all other tablet drivers, it worked previously before installing my second monitor.

**Comment by X9VoiD** [comment]
G430/S config also got updated so download [.NET 5](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.1-windows-x64-installer) and try [OTD v0.5.0 pre-release](https://discord.com/channels/615607687467761684/615939905566015493/794446989739294780).
