### ISSUE TITLE
Support Request: Where can I find v0.5 ?

### ISSUE THREAD

**Issue by UsaidMuhammad** [InfinityGhost/OpenTabletDriver#646]
# Support Request
Need to download v0.5

## What I've already tried
Checked both OTD released and its installer releases no 0.5 tags or release to be found
![image](https://user-images.githubusercontent.com/19373627/104474058-71307080-55df-11eb-85bc-24cbb493ff03.png)

![image](https://user-images.githubusercontent.com/19373627/104474126-84dbd700-55df-11eb-853a-fdd8e3d7e8c0.png)

**Comment by gonX** [comment]
Under [Actions](https://github.com/InfinityGhost/OpenTabletDriver/actions). 0.5.0 hasn't been finalized yet.

**Comment by UsaidMuhammad** [comment]
Apologies for my incompetence, but may I request a few more hand-holding as I am unable to find a place in action to get the v0.5 build.

Do I have to clone master or action and build it myself?

**Comment by X9VoiD** [comment]
Prebuilts for 0.5.0 prerelease can be found on the official [OTD discord server](https://discord.com/channels/615607687467761684/615939905566015493/794446989739294780).

**Comment by gonX** [comment]
> I am unable to find a place in action to get the v0.5 build
From that site you have to click a commit for which artifacts have been generated. Once you're on a commit page, there should be artifacts listed at the bottom with links to the precompiled builds.

I suggest using the pre-release files found on the OTD discord server as suggested by X9VoiD above, as they have the added bonus of being more widely used, so bugs are more predictable.

**Comment by UsaidMuhammad** [comment]
Thanks for the support!
