### ISSUE TITLE
Huion NEW1060 Plus 8192 pressure model does not detect

### ISSUE THREAD

**Issue by CyraMayCry** [InfinityGhost/OpenTabletDriver#647]
## Description
Huion NEW1060 Plus 8192 pressure model is not being detected by the software

## System Information:
| Operating System | Windows 10 64 bit
| Software Version | OpenTabletDriver v0.4.1
| Tablet           | Huion NEW1060 Plus

**Comment by CyraMayCry** [comment]
wait the software version is 0.4.2

**Comment by Mrcubix** [comment]
a diagnostic of the tablet via OTD is required and asked for in the template, please provide that piece of information before we can proceed

**Comment by CyraMayCry** [comment]
{
  "App Version": "OpenTabletDriver v0.4.2",
  "Operating System": {
    "Platform": 2,
    "ServicePack": "",
    "Version": "10.0.19041.0",
    "VersionString": "Microsoft Windows NT 10.0.19041.0"
  },
  "Environment Variables": {
    "USERDOMAIN": "DESKTOP-ES4H99K",
    "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
    "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
    "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 158 Stepping 10, GenuineIntel",
    "Path": "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps;",
    "SESSIONNAME": "Console",
    "GOOGLE_DEFAULT_CLIENT_ID": "no",
    "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-ES4H99K",
    "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
    "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe",
    "OS": "Windows_NT",
    "TMP": "C:\\Users\\User\\AppData\\Local\\Temp",
    "ProgramFiles": "C:\\Program Files",
    "OneDrive": "C:\\Users\\User\\OneDrive",
    "OneDriveConsumer": "C:\\Users\\User\\OneDrive",
    "PROCESSOR_ARCHITECTURE": "AMD64",
    "GOOGLE_DEFAULT_CLIENT_SECRET": "no",
    "PROCESSOR_REVISION": "9e0a",
    "ProgramW6432": "C:\\Program Files",
    "ALLUSERSPROFILE": "C:\\ProgramData",
    "CommonProgramW6432": "C:\\Program Files\\Common Files",
    "USERNAME": "User",
    "PUBLIC": "C:\\Users\\Public",
    "HOMEPATH": "\\Users\\User",
    "COMPUTERNAME": "DESKTOP-ES4H99K",
    "TEMP": "C:\\Users\\User\\AppData\\Local\\Temp",
    "ProgramData": "C:\\ProgramData",
    "LOGONSERVER": "\\\\DESKTOP-ES4H99K",
    "USERPROFILE": "C:\\Users\\User",
    "FPS_BROWSER_USER_PROFILE_STRING": "Default",
    "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
    "SystemDrive": "C:",
    "APPDATA": "C:\\Users\\User\\AppData\\Roaming",
    "PROCESSOR_LEVEL": "6",
    "HOMEDRIVE": "C:",
    "SystemRoot": "C:\\WINDOWS",
    "CommonProgramFiles": "C:\\Program Files\\Common Files",
    "windir": "C:\\WINDOWS",
    "NUMBER_OF_PROCESSORS": "6",
    "LOCALAPPDATA": "C:\\Users\\User\\AppData\\Local",
    "GOOGLE_API_KEY": "no",
    "ProgramFiles(x86)": "C:\\Program Files (x86)",
    "__COMPAT_LAYER": "DetectorsAppHealth",
    "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
  },
  "HID Devices": [
    {
      "DevicePath": "\\\\?\\hid#hid&col03#1&4784345&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 5,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col04#1&1731f3ea&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 8,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col06#1&2d595ca7&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 33,
      "MaxOutputReportLength": 65,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col04#1&4784345&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 8,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col06#1&1731f3ea&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 33,
      "MaxOutputReportLength": 65,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col04#1&2d595ca7&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 8,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#vid_046d&pid_0100&mi_01&col01#8&12b37081&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 1133,
      "ProductID": 256,
      "ReleaseNumberBcd": 289,
      "ReleaseNumber": "1.21",
      "ProductVersion": 289,
      "Manufacturer": "Logitech",
      "ProductName": "G100 Gaming Keyboard",
      "SerialNumber": "",
      "MaxInputReportLength": 5,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col05#1&1731f3ea&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 65,
      "MaxOutputReportLength": 65,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col05#1&4784345&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 65,
      "MaxOutputReportLength": 65,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#vid_046d&pid_0100&mi_01&col02#8&12b37081&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 1133,
      "ProductID": 256,
      "ReleaseNumberBcd": 289,
      "ReleaseNumber": "1.21",
      "ProductVersion": 289,
      "Manufacturer": "Logitech",
      "ProductName": "G100 Gaming Keyboard",
      "SerialNumber": "",
      "MaxInputReportLength": 2,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#vid_1bcf&pid_08a0&col02#7&f067f3c&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd",
      "VendorID": 7119,
      "ProductID": 2208,
      "ReleaseNumberBcd": 260,
      "ReleaseNumber": "1.4",
      "ProductVersion": 260,
      "Manufacturer": "",
      "ProductName": "",
      "SerialNumber": "",
      "MaxInputReportLength": 8,
      "MaxOutputReportLength": 2,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#vid_1bcf&pid_08a0&col01#7&f067f3c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 7119,
      "ProductID": 2208,
      "ReleaseNumberBcd": 260,
      "ReleaseNumber": "1.4",
      "ProductVersion": 260,
      "Manufacturer": "",
      "ProductName": "",
      "SerialNumber": "",
      "MaxInputReportLength": 7,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col03#1&1731f3ea&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 5,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col06#1&4784345&0&0005#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 33,
      "MaxOutputReportLength": 65,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#vid_256c&pid_006e&mi_01#9&28afeb4c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 9580,
      "ProductID": 110,
      "ReleaseNumberBcd": 12288,
      "ReleaseNumber": "30.0",
      "ProductVersion": 12288,
      "Manufacturer": "",
      "ProductName": "",
      "SerialNumber": "",
      "MaxInputReportLength": 8,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col01#1&4784345&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 0,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 3
    },
    {
      "DevicePath": "\\\\?\\hid#vid_046d&pid_0100&mi_00#8&368aae43&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd",
      "VendorID": 1133,
      "ProductID": 256,
      "ReleaseNumberBcd": 289,
      "ReleaseNumber": "1.21",
      "ProductVersion": 289,
      "Manufacturer": "Logitech",
      "ProductName": "G100 Gaming Keyboard",
      "SerialNumber": "",
      "MaxInputReportLength": 9,
      "MaxOutputReportLength": 2,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col01#1&2d595ca7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 0,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 3
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col02#1&4784345&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 7,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col01#1&1731f3ea&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 0,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 3
    },
    {
      "DevicePath": "\\\\?\\hid#vid_1bcf&pid_08a0&col04#7&f067f3c&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 7119,
      "ProductID": 2208,
      "ReleaseNumberBcd": 260,
      "ReleaseNumber": "1.4",
      "ProductVersion": 260,
      "Manufacturer": "",
      "ProductName": "",
      "SerialNumber": "",
      "MaxInputReportLength": 0,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 8
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col02#1&2d595ca7&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 7,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col02#1&1731f3ea&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 7,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col03#1&2d595ca7&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 5,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#hid&col05#1&2d595ca7&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 255,
      "ProductID": 47820,
      "ReleaseNumberBcd": 1,
      "ReleaseNumber": "0.1",
      "ProductVersion": 1,
      "Manufacturer": "DJP Inc.",
      "ProductName": "Virtual Multitouch Device",
      "SerialNumber": "123123123",
      "MaxInputReportLength": 65,
      "MaxOutputReportLength": 65,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "\\\\?\\hid#vid_1bcf&pid_08a0&col03#7&f067f3c&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "VendorID": 7119,
      "ProductID": 2208,
      "ReleaseNumberBcd": 260,
      "ReleaseNumber": "1.4",
      "ProductVersion": 260,
      "Manufacturer": "",
      "ProductName": "",
      "SerialNumber": "",
      "MaxInputReportLength": 3,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    }
  ],
  "Console Log": [
    {
      "Time": "2021-01-15T02:42:15.7303755+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon 1060 Pro'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7303988+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon M106K'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304067+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon S56K'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304132+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon S620'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304273+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H430P'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304349+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H610 Pro V2'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304431+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H610 Pro'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304495+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H640P'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304558+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion HS610'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304625+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion HS611'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304689+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion HS64'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304753+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion Inspiroy Q11K'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304816+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion New 1060 Plus'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304878+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion osu!tablet'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7304941+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion Q620M'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305008+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK A15 Pro'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305082+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK A15'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305174+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK A30'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305242+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK A50'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305305+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK S640'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305369+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTE-430'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305435+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTE-440'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305497+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-470'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305561+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-480'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305624+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-490'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.730569+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-670'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305759+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-680'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7305835+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-690'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7306211+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-4100 Bluetooth'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.730639+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-4100'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7306485+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-4100WL'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.730657+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-460'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7306649+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-470'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7306733+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-471'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7306812+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-472'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7306891+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-480'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7306968+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-490'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307056+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-6100'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307134+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-671'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307205+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-672'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.730727+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-680'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307333+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-690'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307395+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom FT-0405-U'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307457+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-451'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307521+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-660 Bluetooth'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307583+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-660'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307646+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-850'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.730771+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Deco 01 v2'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307781+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Deco 01'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307845+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Deco 02'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307908+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Deco 03'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7307971+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G430'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308034+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G430S'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308097+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G430S_B'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.730816+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G540 Pro'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308224+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G640 v2'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308286+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G640'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308349+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G640s'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308412+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G960 v2'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308483+08:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Star 03v2'",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308547+08:00",
      "Group": "Detect",
      "Message": "No tablet found.",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308612+08:00",
      "Group": "Display",
      "Message": "DPI Awareness enabled",
      "Level": 0
    },
    {
      "Time": "2021-01-15T02:42:15.7308675+08:00",
      "Group": "Settings",
      "Message": "Output mode: OpenTabletDriver.Output.AbsoluteMode",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308737+08:00",
      "Group": "Settings",
      "Message": "Display area: [1920x1080@<960, 540>:0°],",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308801+08:00",
      "Group": "Settings",
      "Message": "Tablet area: [0x0@<0, 0>:0°],",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7308865+08:00",
      "Group": "Display",
      "Message": "DPI Awareness enabled",
      "Level": 0
    },
    {
      "Time": "2021-01-15T02:42:15.7308928+08:00",
      "Group": "Settings",
      "Message": "Clipping: Enabled",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.730899+08:00",
      "Group": "Settings",
      "Message": "Ignoring reports outside area: Disabled",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7309051+08:00",
      "Group": "Settings",
      "Message": "Tip Binding: 'Mouse Button Binding: Left'@1%",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7309123+08:00",
      "Group": "Settings",
      "Message": "Pen Bindings: [0, ], [1, ]",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7309186+08:00",
      "Group": "Settings",
      "Message": "Express Key Bindings: [0, ], [1, ], [2, ], [3, ], [4, ], [5, ]",
      "Level": 1
    },
    {
      "Time": "2021-01-15T02:42:15.7309249+08:00",
      "Group": "Settings",
      "Message": "Driver is auto-enabled.",
      "Level": 1
    }
  ]
}

**Comment by CyraMayCry** [comment]
this one?

**Comment by Mrcubix** [comment]
delete winUSB then huion drivers in that order. reinstall if winUSB is still present.

after that:

Device Manager -> View -> Devices by Container
Find for any of these devices:
  -  Gaomon HID/Tablet
  -  Huion HID/Tablet
  -  Graphics Tablet Device
  -  HID Tablet
Expand drop down then right click on matching device
Click Update -> "Browse my computer" -> "Let me pick" -> HID-compliant device or USB Input Device

install https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.2-windows-x64-installer
then update to that build https://github.com/InfinityGhost/OpenTabletDriver/suites/1831266993/artifacts/35353847

**Comment by CyraMayCry** [comment]
How do i find winUSB and the huion drivers location in the directory?

**Comment by Mrcubix** [comment]
like any program, in "change or uninstall a program"

**Comment by CyraMayCry** [comment]
same with huion drivers?

**Comment by CyraMayCry** [comment]
nvm But theres no either of the devices as the one u listed above

**Comment by Mrcubix** [comment]
just proceed with the next steps which is installing the right dotnet and the pre-release

install https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.2-windows-x64-installer
then update to that build https://github.com/InfinityGhost/OpenTabletDriver/suites/1831266993/artifacts/35353847

**Comment by CyraMayCry** [comment]
ok it works now thx

**Comment by Mrcubix** [comment]
you may close this issue now

**Comment by CyraMayCry** [comment]
can i still use this driver if huion driver is installed?

**Comment by Mrcubix** [comment]
No

**Comment by CyraMayCry** [comment]
aw thats bummer ok then
