### ISSUE TITLE
Username with space fails to open plugin directory

### ISSUE THREAD

**Issue by ssudo-Dev** [InfinityGhost/OpenTabletDriver#652]
## Description
I cant open plugin directory because my username has a space

## System Information:

I use the gaomon s620 and im trying to install plugins

**Comment by X9VoiD** [comment]
This is a bug already fixed on pre-releases. Download [v0.5.0 pre-release](https://discord.com/channels/615607687467761684/615939905566015493/794446989739294780) if you wanna try it out.

**Comment by InfinityGhost** [comment]
Closing as it is a duplicate.
