### ISSUE TITLE
Support Request: CTL-472 not detecting, previously did

### ISSUE THREAD

**Issue by mazziechai** [InfinityGhost/OpenTabletDriver#653]
# Support Request
Hello! I use a CTL-472, and recently the tablet driver has stopped detecting the tablet despite it working perfectly fine before just two days ago.

## What I've already tried
Restarting computer, reinstalling OpenTabletDriver, uninstalling the built in Windows drivers for the tablet. Please keep in mind that this is a brand new tablet; I've only used it for about a few days until this happened, so I'd like to believe that it's not the tablet's fault.

## Diagnostic Information
https://paste.gg/p/anonymous/743a469ef7ba432798c11f1104628ebe

**Comment by X9VoiD** [comment]
You most likely played around with tablet configuration since OTD searches for a non-existent tablet. Reinstall OTD.

**Comment by X9VoiD** [comment]
Just to be entirely sure, open a cmd prompt and run the following command

```
taskkill /IM OpenTabletDriver.Daemon.exe /F >nul 2>nul
taskkill /IM OpenTabletDriver.UX.Wpf.exe /F >nul 2>nul
rmdir /S /Q "%localappdata%\OpenTabletDriver"
```
and then you may install OTD again

**Comment by mazziechai** [comment]
> 
> 
> You most likely played around with tablet configuration since OTD searches for a non-existent tablet. Reinstall OTD.

This was the issue, thanks. I feel silly now.
