### ISSUE TITLE
The software doesn't want to start after running it, it immediately closes. 

### ISSUE THREAD

**Issue by TALOS-BM** [InfinityGhost/OpenTabletDriver#673]
## Description
Every other window I have loses focus after 2-3 seconds until I run the software.
Also, from today (nothing has changed), the software just doesn't want to start, this happens ever since i updated it to 0.42, and now it doesn't let me run earlier versions either.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Windows 10 64bit |
| 0.42 |
| Gaomon S620          |

**Comment by InfinityGhost** [comment]
Well that works out, because we just released v0.5.0. Try that version.

**Comment by TALOS-BM** [comment]
Works perfectl now. Appriciated.
