### ISSUE TITLE
Support Request: cant start up opentabletdriver

### ISSUE THREAD

**Issue by invoke2** [InfinityGhost/OpenTabletDriver#676]
# Support Request
i updated to the latest release just recently and it asked me to redownload NET, which i did. i tried starting it up after but it says 
'opentabletdriver should not be run with administator privileges'

## What I've already tried
i right clicked opentabletdriver and clicked on properties to make sure that 'run as admin' isn't on and i still can't start it up without the error popping up.

## 
Diagnostic Information
can't start up in the first place so i have no diagnostic information

**Comment by X9VoiD** [comment]
Enable UAC

**Comment by invoke2** [comment]
sorry, what's UAC?

**Comment by invoke2** [comment]
works now, thanks!
