### ISSUE TITLE
Add the need to unload the "wacom" driver to the Linux wiki

### ISSUE THREAD

**Issue by Kodehawa** [InfinityGhost/OpenTabletDriver#68]
## Description

For the best experience, specially on dual screen systems, I noticed unloading the "wacom" driver gives a way, way smoother experience and avoids the "ghost cursor" that appears on the other screen. 
Basically `sudo rmmod wacom`.
I just made a small bash script to run before OpenTabletDriver but I guess it could be added to the wiki.

You can also add a blacklist rule in `/etc/modprobe.d/`

## System Information:

Option            | Value
------------------|------------------
Operating System  |  Linux
Software Version  |  v0.1.0-rc1
Tablet            |  CTL-480

**Comment by InfinityGhost** [comment]
Noted in the [wiki](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#i-have-a-ghost-cursor-constantly-alternating-cursor-position)

**Comment by InfinityGhost** [comment]
Closing until further notice
