### ISSUE TITLE
I put the plugin into plugin folder doesnt appear error 

### ISSUE THREAD

**Issue by schbs** [InfinityGhost/OpenTabletDriver#682]
## Description

Basically when I put the plugin into plugin folder, but its still doesnt view in OpenTabletDriver App (sorry about my english)
![image_2021-01-20_060129](https://user-images.githubusercontent.com/77722780/105151629-f090d900-5ae4-11eb-94ee-46389cb2205b.png)
![image_2021-01-20_060206](https://user-images.githubusercontent.com/77722780/105151704-07373000-5ae5-11eb-9437-934014b055d4.png)

## System Information:

| Name   Ger          | Value |
| ---------------- | ----- |
| Operating System | Windows 10
| Software Version | 0.4.1
| Tablet           | Intuos S Wacom

**Comment by InfinityGhost** [comment]
The plugin installation method has changed, you would drag and drop the dll into the plugin manager window. However, this does bring to my attention a bug revolving around showing manually installed plugins.

**Comment by InfinityGhost** [comment]
Going to open a separate issue for that bug.
