### ISSUE TITLE
Pen pressing bug

### ISSUE THREAD

**Issue by eternaLife1337** [InfinityGhost/OpenTabletDriver#712]
## Description
Pen pressing stopped working after updating the program to version 0.5.0
(not the pen buttons, namely the pen press)
## System Information:
| Operating System |
Windows 10
| Software Version |
0.5.0
| Tablet |
Gaomon S620

**Comment by Mrcubix** [comment]
not a bug, formatting has been changed and therefore, the tip got unbound, go back to binding tab and bind it there

**Comment by eternaLife1337** [comment]
oh, i tried to bind this once and didn't helped, now for some reason it's working. Anyway thanks
