### ISSUE TITLE
Manual service restart needed

### ISSUE THREAD

**Issue by Arisuuuuu** [InfinityGhost/OpenTabletDriver#733]
## Description
After reboot I need to manually restart the the daemon so it detects the tablet. Works fine then.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| OS | Manjaro 20.2 |
| OTD-Version  | v0.5-r59|
| Tablet | CTH-480      |

**Comment by LavaDesu** [comment]
I assume you installed OTD from the AUR? I just pushed an update that should fix this issue (make sure to run the commands in the post-upgrade message)

**Comment by Arisuuuuu** [comment]
thanks, that did fix it!
i will close this issue
