### ISSUE TITLE
Support Request: No tablet found.

### ISSUE THREAD

**Issue by Enzyoo** [InfinityGhost/OpenTabletDriver#737]
My CTL 480 tablet is not detected. Works fine using Wacom drivers.

Console log: 

> [Detect:Info]	Searching for tablet 'Gaomon 1060 Pro'
> [Detect:Info]	Searching for tablet 'Gaomon M106K'
> [Detect:Info]	Searching for tablet 'Gaomon S56K'
> [Detect:Info]	Searching for tablet 'Gaomon S620'
> [Detect:Info]	Searching for tablet 'Huion GT-133'
> [Detect:Info]	Searching for tablet 'Huion H1060P'
> [Detect:Info]	Searching for tablet 'Huion H430P'
> [Detect:Info]	Searching for tablet 'Huion H610 Pro V2'
> [Detect:Info]	Searching for tablet 'Huion H610 Pro'
> [Detect:Info]	Searching for tablet 'Huion H640P'
> [Detect:Info]	Searching for tablet 'Huion HS610'
> [Detect:Info]	Searching for tablet 'Huion HS611'
> [Detect:Info]	Searching for tablet 'Huion HS64'
> [Detect:Info]	Searching for tablet 'Huion Inspiroy Q11K V2'
> [Detect:Info]	Searching for tablet 'Huion Inspiroy Q11K'
> [Detect:Info]	Searching for tablet 'Huion New 1060 Plus'
> [Detect:Info]	Searching for tablet 'Huion osu!tablet'
> [Detect:Info]	Searching for tablet 'Huion Q620M'
> [Detect:Info]	Searching for tablet 'VEIKK A15 Pro'
> [Detect:Info]	Searching for tablet 'VEIKK A15'
> [Detect:Info]	Searching for tablet 'VEIKK A30'
> [Detect:Info]	Searching for tablet 'VEIKK A50'
> [Detect:Info]	Searching for tablet 'VEIKK S640'
> [Detect:Info]	Searching for tablet 'Wacom CTE-430'
> [Detect:Info]	Searching for tablet 'Wacom CTE-440'
> [Detect:Info]	Searching for tablet 'Wacom CTE-460'
> [Detect:Info]	Searching for tablet 'Wacom CTE-650'
> [Detect:Info]	Searching for tablet 'Wacom CTH-460'
> [Detect:Info]	Searching for tablet 'Wacom CTH-470'
> [Detect:Info]	Searching for tablet 'Wacom CTH-480'
> [Detect:Info]	Searching for tablet 'Wacom CTH-490'
> [Detect:Info]	Searching for tablet 'Wacom CTH-670'
> [Detect:Info]	Searching for tablet 'Wacom CTH-680'
> [Detect:Info]	Searching for tablet 'Wacom CTH-690'
> [Detect:Info]	Searching for tablet 'Wacom CTL-4100 Bluetooth'
> [Detect:Info]	Searching for tablet 'Wacom CTL-4100'
> [Detect:Info]	Searching for tablet 'Wacom CTL-4100WL'
> [Detect:Info]	Searching for tablet 'Wacom CTL-460'
> [Detect:Info]	Searching for tablet 'Wacom CTL-470'
> [Detect:Info]	Searching for tablet 'Wacom CTL-471'
> [Detect:Info]	Searching for tablet 'Wacom CTL-472'
> [Detect:Info]	Searching for tablet 'Wacom CTL-480'
> [IOException:Error]	SetFeature failed.
> [Detect:Info]	Searching for tablet 'Wacom CTL-490'
> [Detect:Info]	Searching for tablet 'Wacom CTL-6100'
> [Detect:Info]	Searching for tablet 'Wacom CTL-671'
> [Detect:Info]	Searching for tablet 'Wacom CTL-672'
> [Detect:Info]	Searching for tablet 'Wacom CTL-680'
> [Detect:Info]	Searching for tablet 'Wacom CTL-690'
> [Detect:Info]	Searching for tablet 'Wacom FT-0405-U'
> [Detect:Info]	Searching for tablet 'Wacom MTE-450'
> [Detect:Info]	Searching for tablet 'Wacom PTH-451'
> [Detect:Info]	Searching for tablet 'Wacom PTH-651'
> [Detect:Info]	Searching for tablet 'Wacom PTH-660 Bluetooth'
> [Detect:Info]	Searching for tablet 'Wacom PTH-660'
> [Detect:Info]	Searching for tablet 'Wacom PTH-850'
> [Detect:Info]	Searching for tablet 'Wacom PTH-860'
> [Detect:Info]	Searching for tablet 'Wacom PTK-1240'
> [Detect:Info]	Searching for tablet 'Wacom PTK-440'
> [Detect:Info]	Searching for tablet 'Wacom PTK-540WL'
> [Detect:Info]	Searching for tablet 'XP-Pen Deco 01 v2'
> [Detect:Info]	Searching for tablet 'XP-Pen Deco 01'
> [Detect:Info]	Searching for tablet 'XP-Pen Deco 02'
> [Detect:Info]	Searching for tablet 'XP-Pen Deco 03'
> [Detect:Info]	Searching for tablet 'XP-Pen G430'
> [Detect:Info]	Searching for tablet 'XP-Pen G430S'
> [Detect:Info]	Searching for tablet 'XP-Pen G540 Pro'
> [Detect:Info]	Searching for tablet 'XP-Pen G540'
> [Detect:Info]	Searching for tablet 'XP-Pen G640 v2'
> [Detect:Info]	Searching for tablet 'XP-Pen G640'
> [Detect:Info]	Searching for tablet 'XP-Pen G640s'
> [Detect:Info]	Searching for tablet 'XP-Pen G960 v2'
> [Detect:Info]	Searching for tablet 'XP-Pen Star 03'
> [Detect:Info]	Searching for tablet 'XP-Pen Star 06'
> [Detect:Info]	No tablet found.
> [Settings:Info]	Output mode: Absolute Mode
> [Settings:Info]	Display area: [1920x1080@<960, 540>:0°],
> [Settings:Info]	Tablet area: [0x0@<0, 0>:0°],
> [Settings:Info]	Clipping: Enabled
> [Settings:Info]	Ignoring reports outside area: Disabled
> [Settings:Info]	Tip Binding: [Mouse Button Binding: Left]@1%
> [Settings:Info]	Pen Bindings: [0, ], [1, ]
> [Settings:Info]	Express Key Bindings: [0, ], [1, ], [2, ], [3, ], [4, ], [5, ]
> [Settings:Info]	Driver is auto-enabled.

**Comment by X9VoiD** [comment]
Uninstall wacom driver then replug tablet
