### ISSUE TITLE
Gaomon S620 pen not clicking

### ISSUE THREAD

**Issue by deportedboi** [InfinityGhost/OpenTabletDriver#739]
## Description

The pen doesn't register a click when it is in contact with the tablet. It tracks just fine but when I press on the tablet I can't draw or click on anything.
Tried reinstalling but still didn't work.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10 |
| Software Version | v0.5.1 |
| Tablet           | Gaomon s620 |

**Comment by gonX** [comment]
Did you assign the tip button to an action under Bindings?

**Comment by deportedboi** [comment]
oh my god, I didn't know that was a thing. It was working before v0.5.0 so I guess it was recently added.
Thanks.
