### ISSUE TITLE
Hey, Just a quick question!

### ISSUE THREAD

**Issue by brotherhooder** [InfinityGhost/OpenTabletDriver#743]
Hello there mate!,
I've been wondering when will be a Area Calculator suggestion added, On page it says 5.0, I've requested this feature myself, And apparently other people too have requested it too, If it has been implemented how does it exactly work?
Sorry for the Impatience.
Thanks!

**Comment by brotherhooder** [comment]
Also sorry if I didn't tag it correctly, I don't really know where this goes on exactly

**Comment by InfinityGhost** [comment]
On v0.5+, you right click the tablet area display to get the context menu. This is where you can find the area converter.

**Comment by brotherhooder** [comment]
Thanks.
