### ISSUE TITLE
Support Request: Tablet listed as supported not found (Wacom CTL-672 on macOS Catalina 10.15.6)

### ISSUE THREAD

**Issue by gionimbus** [InfinityGhost/OpenTabletDriver#757]
# Support Request

Hello everyone, 
I run macOS Catalina 10.15.6 and have downloaded OpenTabletDriver v0.5.1. When I plug in my Wacom tablet (CTL-672), the driver does not detect it. Same message shown even in the console. I have not installed any other driver on my computer. My tablet works fine (tried it on another computer). 

Thank you

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, upload the generated file here.

**Comment by gionimbus** [comment]
{
  "App Version": "OpenTabletDriver v0.5.1",
  "Operating System": {
    "Platform": 4,
    "ServicePack": "",
    "Version": "10.15.6",
    "VersionString": "Unix 10.15.6"
  },
  "Environment Variables": {
    "HOME": "/Users/giovannilupi",
    "TMPDIR": "/var/folders/64/p8bvn7sj2jn7q3brm_g9yhnc0000gn/T/",
    "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.HMjKq1YY1Y/Listeners",
    "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
    "SHELL": "/bin/zsh",
    "XPC_SERVICE_NAME": "com.infinityghost.opentabletdriver.8248",
    "LOGNAME": "giovannilupi",
    "XPC_FLAGS": "0x0",
    "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x4",
    "USER": "giovannilupi"
  },
  "HID Devices": [
    {
      "DevicePath": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Actuator/AppleHSSPIHIDDriver",
      "VendorID": 1452,
      "ProductID": 627,
      "ReleaseNumberBcd": 1570,
      "CanOpen": true,
      "ReleaseNumber": "6.22",
      "ProductVersion": 1570,
      "Manufacturer": "",
      "ProductName": "Apple Internal Keyboard / Trackpad",
      "SerialNumber": "",
      "MaxInputReportLength": 16,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Device Management/AppleHSSPIHIDDriver",
      "VendorID": 1452,
      "ProductID": 627,
      "ReleaseNumberBcd": 1570,
      "CanOpen": true,
      "ReleaseNumber": "6.22",
      "ProductVersion": 1570,
      "Manufacturer": "",
      "ProductName": "Apple Internal Keyboard / Trackpad",
      "SerialNumber": "",
      "MaxInputReportLength": 5,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/CTL-672@14200000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice",
      "VendorID": 1386,
      "ProductID": 891,
      "ReleaseNumberBcd": 256,
      "CanOpen": true,
      "ReleaseNumber": "1.0",
      "ProductVersion": 256,
      "Manufacturer": "Wacom Co.,Ltd.",
      "ProductName": "CTL-672",
      "SerialNumber": "0LE00M1094328",
      "MaxInputReportLength": 64,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    },
    {
      "DevicePath": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@15,4/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Accelerometer/AppleHSSPIHIDDriver",
      "VendorID": 1452,
      "ProductID": 627,
      "ReleaseNumberBcd": 1570,
      "CanOpen": true,
      "ReleaseNumber": "6.22",
      "ProductVersion": 1570,
      "Manufacturer": "",
      "ProductName": "Apple Internal Keyboard / Trackpad",
      "SerialNumber": "",
      "MaxInputReportLength": 108,
      "MaxOutputReportLength": 0,
      "MaxFeatureReportLength": 0
    }
  ],
  "Console Log": [
    {
      "Time": "2021-02-04T21:15:41.05908+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G430'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059124+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G430S'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059153+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Star 03'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059176+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G640'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059199+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Deco 01'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05922+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Artist Pro 12'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059236+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Deco 02'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059253+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G540 Pro'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059268+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Deco Mini7'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05928+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Deco 03'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05929+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G640s'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059301+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Star 06'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059312+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen Deco 01 v2'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05932+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G960 v2'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059331+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G540'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059343+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'XP-Pen G640 v2'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05935+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon S620'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059359+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon M106K'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059367+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon M106K Pro'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059375+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon S56K'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059384+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon 1060 Pro'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059395+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK A15'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059403+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK S640'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059411+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK A30'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059418+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK A50'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059426+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'VEIKK A15 Pro'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059434+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-660'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059441+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-480'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059449+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-680'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059477+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-460'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059486+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTE-650'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059496+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-860'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059504+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-660 Bluetooth'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059512+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTE-430'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05952+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-490'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059527+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-670'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059537+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-451'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059545+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTE-440'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059552+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTE-460'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05956+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-672'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059567+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-472'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059576+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-4100 Bluetooth'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059584+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-470'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059591+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-850'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059599+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-690'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059606+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTH-651'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059614+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom FT-0405-U'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059622+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTK-440'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059629+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-490'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059637+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-6100'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059645+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-471'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059652+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-470'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059661+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-4100WL'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059669+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-690'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059676+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-671'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059684+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTK-540WL'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059691+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-480'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059699+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom PTK-1240'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059706+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom MTE-450'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059713+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTH-680'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059721+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-460'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059729+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Wacom CTL-4100'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059736+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion Q620M'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059745+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion HS611'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059753+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H1060P'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05976+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H1161'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059768+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H430P'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059775+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion HS610'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059783+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion New 1060 Plus'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05979+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion osu!tablet'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059798+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion Inspiroy Q11K V2'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059805+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H640P'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059813+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H610 Pro V2'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059822+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion HS64'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05983+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion GT-133'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059837+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion Inspiroy Q11K'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059845+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion G10T'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059852+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion H610 Pro'",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059859+01:00",
      "Group": "Detect",
      "Message": "No tablet found.",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059867+01:00",
      "Group": "Settings",
      "Message": "Output mode: Absolute Mode",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059874+01:00",
      "Group": "Settings",
      "Message": "Display area: [1280x800@<640, 400>:0°],",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059881+01:00",
      "Group": "Settings",
      "Message": "Tablet area: [0x0@<0, 0>:0°],",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059888+01:00",
      "Group": "Settings",
      "Message": "Clipping: Enabled",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059896+01:00",
      "Group": "Settings",
      "Message": "Ignoring reports outside area: Disabled",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059905+01:00",
      "Group": "Settings",
      "Message": "Tip Binding: [Mouse Button Binding: Left]@1%",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059912+01:00",
      "Group": "Settings",
      "Message": "Pen Bindings: [0, ], [1, ]",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.05992+01:00",
      "Group": "Settings",
      "Message": "Express Key Bindings: [0, ], [1, ], [2, ], [3, ], [4, ], [5, ]",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059927+01:00",
      "Group": "Settings",
      "Message": "Driver is auto-enabled.",
      "Level": 1
    },
    {
      "Time": "2021-02-04T21:15:41.059935+01:00",
      "Group": "IPC",
      "Message": "Connected to a client.",
      "Level": 0
    }
  ]
}


Sorry for the copy-paste but GitHub does not accept a .json file. Thank you very much.

**Comment by gionimbus** [comment]
[Untitled.json.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5928291/Untitled.json.zip)

**Comment by gionimbus** [comment]
Any idea about what it could be?

**Comment by X9VoiD** [comment]
OTD diagnostics show that you are missing a CTL-672 endpoint, are you sure you have no other driver running in your system?

**Comment by gionimbus** [comment]
Yeah pretty sure, I disinstalled the wacom drivers and also I manually checked the directories where there could be some remaining files. I didn't find any.
