### ISSUE TITLE
The installer will not launch without admin privileges.

### ISSUE THREAD

**Issue by adxv** [InfinityGhost/OpenTabletDriver#767]
The issue is likely caused by having the UAC disabled.

Workaround: Create a bat file with the following command(replace the location of the installer): 
`runas /trustlevel:0x20000 C:\Users\adams\Downloads\OpenTabletDriver.Installer.exe`

**Comment by AbstractQbit** [comment]
This is looks like a duplicate of #681.

**Comment by adxv** [comment]
Thank you and sorry.
