### ISSUE TITLE
Wacom CTL-472 wont detect in the driver. 

### ISSUE THREAD

**Issue by Mizzat1** [InfinityGhost/OpenTabletDriver#772]
# Support Request

**Comment by X9VoiD** [comment]
Please fill in all other information required by the template.

But in any case, update to OTD 0.5.1 to fix double initialization issue when running OTD while wacom driver is installed.

**Comment by gionimbus** [comment]
I have the same problem with the same tablet model. No other driver installed.

**Comment by X9VoiD** [comment]
@gionimbus Please upload diagnostics (OTD -> Help -> Export Diagnostics)

**Comment by InfinityGhost** [comment]
Template didn't provide any data, and no recent response. Assuming it was self-resolved.
