### ISSUE TITLE
Support Request: Area properties not working

### ISSUE THREAD

**Issue by SpoonMcForky** [InfinityGhost/OpenTabletDriver#776]
# Support Request
 The Tablet Area settings don't do anything, with the area set up it still maps the entire tablet to all of my monitors.

![image](https://user-images.githubusercontent.com/55011606/108098530-7dca3d80-7051-11eb-9fba-cead600015a3.png) 
I've made my area and right clicked the upper gui to set which monitor and chose which monitor I wanted (I selected monitor 1 but that isn't even my main monitor)

## What I've already tried
 I've restarted my PC, the Wacom drivers are not running.

## Diagnostic Information

[OTDDiag.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5990398/OTDDiag.zip)

**Comment by SpoonMcForky** [comment]
It's the same when it's closed, so does that mean that the tablet is not actually communicating with the driver?

**Comment by Mrcubix** [comment]
if your cursor when moving your pen is a windows cursor, uninstall wacom or disable it's services

**Comment by SpoonMcForky** [comment]
Also with the Wacom drivers running and OTD _uninstalled_ 2 cursers appear on the screen

**Comment by Mrcubix** [comment]
double init issue fixed in dev builds https://github.com/InfinityGhost/OpenTabletDriver/actions

unplug your tablet and it will be fixed

**Comment by InfinityGhost** [comment]
7 days since last response, assuming resolved.
