### ISSUE TITLE
Multiple cursors flickering

### ISSUE THREAD

**Issue by MelonIs45** [InfinityGhost/OpenTabletDriver#778]
## Description

When I tried adjusting my area, applied and then while I'm using the tablet my cursor flickers between the point it would be at if my area wasn't adjusted and the area when it is adjusted, its quite a strange behavior, I haven't installed any Wacom drivers on this system so I'm guessing its an issue with OTD.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Ubuntu 20.04
| Software Version | 0.5.1
| Tablet           | Wacom CTL-480

**Comment by MelonIs45** [comment]
I have also now noticed that it happens when my cursor stays in one place for around any period of time, might help

**Comment by AbstractQbit** [comment]
https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#i-have-a-ghost-cursor-constantly-alternating-cursor-position

**Comment by MelonIs45** [comment]
Thank you! I should really read everything there is before submitting anything :P
