### ISSUE TITLE
Offset with Windows' rearranged displays

### ISSUE THREAD

**Issue by joonim123** [InfinityGhost/OpenTabletDriver#789]
## Description

I have given my 2nd display a marginal offset(vertical) to minimize the cursor teleporting whenever it decides to travel between the two.

OTD doesn't seem to consider rearrangement, and snaps perfectly in the bottom, according to the debugger and the gui. This leads to not being able to use a portion of your [intended](https://i.imgur.com/yZ1Oxa6.png) area, if you've rearranged the displays in certain ways in Windows.

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10 Home 64-bit
| Software Version | v0.5.1
| Tablet           | Wacom CTL-480

**Comment by InfinityGhost** [comment]
Is this a display resolution, position, or arrangement change while OpenTabletDriver is running? It currently doesn't support it without a full restart because of a lack of an event source.

**Comment by joonim123** [comment]
Problem seems to be fixed by restarting system, will keep this in mind. Thanks
