### ISSUE TITLE
CTL-480 not detected when using a USB extension cable

### ISSUE THREAD

**Issue by geolan-su** [InfinityGhost/OpenTabletDriver#79]
## Description

When I put the extension cable in, connection goes bye-bye.

## System Information:

Option            | Value
------------------|------------------
Operating System  | Arch Linux x86_64 running gnome-xorg
Software Version  | 0.1.0? latest from AUR
Tablet            | CTL-480

**Comment by InfinityGhost** [comment]
What devices show up in the Configuration Manager?

**Comment by geolan-su** [comment]
issue seemed to have resolved itself after plugging in w/o extender then with.
