### ISSUE TITLE
Huion h1060p not detected

### ISSUE THREAD

**Issue by abcd12345abcd** [InfinityGhost/OpenTabletDriver#802]
I can move around the cursor using the tablet and pressure works, but I can't change any settings. Other then that I have no idea what is going on.

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics

**Comment by abcd12345abcd** [comment]
Done, what next?

**Comment by X9VoiD** [comment]
Upload it here as a zipped file

**Comment by abcd12345abcd** [comment]
[tablet.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/6045103/tablet.zip)

**Comment by Mrcubix** [comment]
AFAIK, it should work, just to make sure, go to Tablet > Device String Reader
the type the following
9580
109
201
send request and paste the obtained string here

**Comment by abcd12345abcd** [comment]
It says "HUION_T205_200714"

**Comment by Mrcubix** [comment]
[H1060P.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/6045204/H1060P.zip)
extract this in Configuration/Huion

**Comment by abcd12345abcd** [comment]
Thank you! I'll try this in a bit and get back.

**Comment by abcd12345abcd** [comment]
...It didn't work. I really have no idea what I've done wrong.

**Comment by Mrcubix** [comment]
AFAIK, if you use 0.5.1 (latest release) and this config it should work else there is a bigger issue that's not related to OTD

**Comment by abcd12345abcd** [comment]
I am using both the latest release and that config, so ig something else is wrong. Thank you anyways!

**Comment by Mrcubix** [comment]
just to make sure, re-upload a diagnostic with this config in the folder

**Comment by abcd12345abcd** [comment]
[tablet2.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/6045377/tablet2.zip)

**Comment by Mrcubix** [comment]
[H1060P.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/6045409/H1060P.zip)
One last attempt at making it work, as i know the previous config will work for other users

**Comment by abcd12345abcd** [comment]
didn't work :/

**Comment by Mrcubix** [comment]
go to tablet > tablet debugger, if you move your pen there, does anything happen

**Comment by abcd12345abcd** [comment]
nope

**Comment by Mrcubix** [comment]
just to make sure, you uninstall WinUSB in programs and features, and uninstalled vmulti if you ever installed it

**Comment by abcd12345abcd** [comment]
Yeah, I did. Well, I assume I did it correctly.

**Comment by Mrcubix** [comment]
well you'll have to wait for void's potential instructions cause i have no idea why your specific H1060P doesn't work rn

**Comment by abcd12345abcd** [comment]
Alright. Thanks for all the help!

**Comment by abcd12345abcd** [comment]
It worked! I have no idea why it wasn't working earlier, but now it's working. Thank you guys so much!

**Comment by InfinityGhost** [comment]
Linking this issue to #803
