### ISSUE TITLE
Tablet Area and Display Area Settings not being applied

### ISSUE THREAD

**Issue by WK-M** [InfinityGhost/OpenTabletDriver#81]
## Description
CTH 470 is being detected according to the console logs however when changing the tablet area on the software and applying the settings, tablet area does not change regardless of the console logs saying that the settings that I had configured had been applied.

Also, I have tried changing the display area and that setting is not applied as well when testing it out with my tablet.

## System Information:
Operating System  | Ubuntu 18.04.3 LTS (Bionic Beaver)
Software Version  | v0.1.0-rc1
Tablet            | CTH 470

**Comment by MoeLava** [comment]
Have you disabled the `wacom` module as per [the FAQ](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#i-have-a-ghost-cursor-constantly-alternating-cursor-position)? Please also make sure you've enabled input hook.

**Comment by WK-M** [comment]
When I disable the wacom module, the tablet is not detected and the tablet is not responsive unless I reconnect it.

**Comment by MoeLava** [comment]
The wacom module is taking control of your tablet, not OpenTabletDriver. Can you enable debugging in the console and see if it outputs anything from your tablet?

**Comment by WK-M** [comment]
With debugging enabled and the wacom module disabled, there are no events that are reported. Even when touching the tablet or hovering the pen, there is no report of some event.

However, after replugging in the tablet, there are reports of outputs from the tablet.

![Screenshot from 2020-01-16 00-55-49](https://user-images.githubusercontent.com/24480278/72497617-f4678c80-37fa-11ea-9231-4a645bc4bc5e.png)

**Comment by WK-M** [comment]
I apologize, I fixed the issue as you stated, I skimmed through your comment and didn't enable input hook. 

> Have you disabled the `wacom` module as per [the FAQ](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#i-have-a-ghost-cursor-constantly-alternating-cursor-position)? Please also make sure you've enabled input hook.
