### ISSUE TITLE
Driver output doesn't position cursor with driver enabled

### ISSUE THREAD

**Issue by pomidorfarm** [InfinityGhost/OpenTabletDriver#82]
## Description

I read Wiki, so I installed xp-pen driver but Cursor do not move.
would you help me ?
(already changed ProductID and ReportLength)
![1](https://user-images.githubusercontent.com/59930799/72527516-4e745a80-38ac-11ea-9602-e02bb26dd3d7.PNG)
![2](https://user-images.githubusercontent.com/59930799/72527543-58965900-38ac-11ea-8ccb-1c1d0cac430e.PNG)
![3](https://user-images.githubusercontent.com/59930799/72527545-5b914980-38ac-11ea-822c-23151500bf61.PNG)
## System Information:

Option            | Value
------------------|------------------
Operating System  | Windows 10
Software Version  | v0.1.0-rc1
Tablet            | XP-Pen Deco 01 v2

**Comment by InfinityGhost** [comment]
Just to make sure, the xp-pen driver is closed, correct?

**Comment by pomidorfarm** [comment]
I closed driver at task manager and disable startup options

**Comment by InfinityGhost** [comment]
I don't see any reason why it shouldn't be positioning your cursor. Try [this build](https://github.com/InfinityGhost/OpenTabletDriver/suites/399041841/artifacts/1105666) and you might have better luck

**Comment by pomidorfarm** [comment]
Not moving.
I tried ↓
deleted Vmulti driver.
installed xp-pen driver,.NET Core 3.0 SDK.
closed xp-pen driver at task manager .
run opentabletdriver ,enable driver.
The tablet is sensing input, but the cursor does not move.
![1](https://user-images.githubusercontent.com/59930799/72663818-f2d7d780-3a39-11ea-8182-3341a065ecaa.PNG)

**Comment by InfinityGhost** [comment]
Once plugin support is added I can better help treat this issue easier without direct contact. For now, the best option to help me mitigate this is to join my [discord](https://discord.gg/P3GYdUS)

**Comment by InfinityGhost** [comment]
Actually scratch that, go into the configuration manager and modify your Deco 01 v2 config to match this, then close the window. It should begin to function after that.
 
![image](https://user-images.githubusercontent.com/39218853/72855269-e5faf400-3c84-11ea-8768-0c5ebb3ff390.png)

**Comment by pomidorfarm** [comment]
It worked , Thank you very much!!!
I joined discord.
Thank you!!!

**Comment by InfinityGhost** [comment]
Reopening this as a reminder to fix the configuration in a future update.

**Comment by InfinityGhost** [comment]
I'm pretty sure I fixed this tablet configuration, so closing this issue.
