### ISSUE TITLE
Incorrect clipping with absolute mode.

### ISSUE THREAD

**Issue by Kodehawa** [InfinityGhost/OpenTabletDriver#83]
## Description
Tablet area clipping goes out of bounds (to the screen it's not supposed to go) with an area <152mm (aka full area) when locked to one screen.
[Attached is the full debug output with a 118mm area set, locked aspect ratio. ](https://github.com/InfinityGhost/OpenTabletDriver/files/4089001/log.log)

Extract from the output:
```
[Normal:Report]    Lift:120, Position:[0,9254], Pressure:0, PenButtons:[False False]
[Normal:Debug]    Cursor Position: 1643.3899,1290.1017
[Normal:Report]    Lift:120, Position:[15087,5205], Pressure:0, PenButtons:[False False]
[Normal:Debug]    Cursor Position: 4099.2,613.70844
```

## System Information:

Option            | Value
------------------|------------------
Operating System  | Linux
Software Version  | latest git from the plugins branch
Tablet            | CTL-480

**Comment by InfinityGhost** [comment]
Misinterpretation of the clipping function. Enabling clipping by default and adding tooltips should help prevent these issues. Not closing this until a tooltip PR is merged.
