### ISSUE TITLE
[CTL 470] Tablet not found (Linux)

### ISSUE THREAD

**Issue by MaxKruse** [InfinityGhost/OpenTabletDriver#85]
## Description
The tablet isnt detected.

Once it gets to the correct tablet, i get following error: 

[Time] | DeviceIOException | Unable to open HID class device (OK)

## System Information:

Option            | Value
------------------|------------------
Linux Manjaro | 18.1.5 KDE Plasma  /   5.4.13-3-MANJARO
Software Version  | 0.1.0-rc1
Tablet            | CTL 470

**Comment by nerd** [comment]
[reading comprehension moment](https://github.com/InfinityGhost/OpenTabletDriver/wiki/Linux-FAQ#the-driver-fails-to-open-the-tablet-deviceioexception)

**Comment by MaxKruse** [comment]
u right me stoopid
